#!/usr/bin/env python3
"""Build the Hybrid Guardrail V3 Ablation Study notebook."""

import json, os

def md(source):
    return {"cell_type": "markdown", "metadata": {}, "source": source if isinstance(source, list) else [source]}

def code(source):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [],
            "source": source if isinstance(source, list) else [source]}

cells = []

# =============================================================================
# CELL 0: Title
# =============================================================================
cells.append(md([
    "# Hybrid Guardrail V3 — Focused Ablation Study\n",
    "\n",
    "**Objective:** Determine which components of Hybrid Guardrail V3 contribute to performance.\n",
    "\n",
    "**Ablations:**\n",
    "- Ablation 0: Full Baseline (TF-IDF + 117 handcrafted + stacking ensemble)\n",
    "- Ablation 1: TF-IDF only (no handcrafted features)\n",
    "- Ablation 2: Handcrafted features only (no TF-IDF)\n",
    "- Ablation 3+: Full minus one feature group at a time\n",
    "\n",
    "**Protocol:** Same dataset, same 70/10/20 stratified split, same classifier, same seed (42)."
]))

# =============================================================================
# CELL 1: Imports + GPU
# =============================================================================
cells.append(code([
    "import gc, re, sys, json, math, time, base64, glob, random, os, hashlib\n",
    "from pathlib import Path\n",
    "from datetime import datetime\n",
    "from collections import Counter\n",
    "from typing import Dict, List, Optional, Set, Tuple\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from sklearn.model_selection import train_test_split, StratifiedKFold\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "from sklearn.ensemble import StackingClassifier, RandomForestClassifier\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.calibration import CalibratedClassifierCV\n",
    "from sklearn.metrics import (\n",
    "    classification_report, confusion_matrix, accuracy_score, f1_score,\n",
    "    precision_score, recall_score, roc_auc_score, matthews_corrcoef,\n",
    "    cohen_kappa_score, balanced_accuracy_score, precision_recall_curve,\n",
    "    average_precision_score, roc_curve,\n",
    ")\n",
    "from scipy.sparse import hstack as sparse_hstack, csr_matrix\n",
    "import xgboost as xgb\n",
    "import lightgbm as lgb\n",
    "import joblib\n",
    "\n",
    "import subprocess\n",
    "subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', 'psutil', 'matplotlib', 'seaborn', 'datasets'],\n",
    "               capture_output=True)\n",
    "import psutil\n",
    "import matplotlib; matplotlib.use('Agg')\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "plt.rcParams['figure.dpi'] = 150; plt.rcParams['savefig.dpi'] = 300\n",
    "plt.rcParams['font.family'] = 'DejaVu Sans'; sns.set_style('whitegrid')\n",
    "\n",
    "# GPU Detection\n",
    "IN_KAGGLE = os.path.exists('/kaggle/input')\n",
    "print(f\"Environment: {'Kaggle' if IN_KAGGLE else 'Local'}\")\n",
    "\n",
    "GPU_NAME = None\n",
    "try:\n",
    "    r = subprocess.run(['nvidia-smi', '--query-gpu=name,memory.total', '--format=csv,noheader'],\n",
    "                       capture_output=True, text=True, timeout=5)\n",
    "    if r.returncode == 0:\n",
    "        parts = r.stdout.strip().split(',')\n",
    "        GPU_NAME = parts[0].strip()\n",
    "        print(f\"GPU: {GPU_NAME}\")\n",
    "except:\n",
    "    print('GPU: detection failed')\n",
    "\n",
    "N_CPU = os.cpu_count()\n",
    "print(f\"CPU cores: {N_CPU}\")\n",
    "ram = psutil.virtual_memory()\n",
    "print(f\"RAM: {ram.total/1e9:.1f}GB (avail: {ram.available/1e9:.1f}GB)\")\n",
    "print('All imports OK')"
]))

# =============================================================================
# CELL 2: Configuration
# =============================================================================
cells.append(code([
    "SEED = 42\n",
    "TFIDF_WORD_MAX = 5000\n",
    "TFIDF_NGRAM = (1, 2)\n",
    "N_ESTIMATORS = 500\n",
    "MAX_DEPTH = 6\n",
    "LR = 0.05\n",
    "\n",
    "# Directories\n",
    "ABLATION_DIR = Path('/kaggle/working/ablation_study') if IN_KAGGLE else Path('ablation_study')\n",
    "RESULTS_DIR = ABLATION_DIR / 'results'\n",
    "CHECKPOINT_DIR = ABLATION_DIR / 'checkpoints'\n",
    "LOG_DIR = ABLATION_DIR / 'logs'\n",
    "FIG_DIR = ABLATION_DIR / 'figures'\n",
    "TABLE_DIR = ABLATION_DIR / 'tables'\n",
    "INTERMEDIATE_DIR = ABLATION_DIR / 'intermediate'\n",
    "MANIFEST_DIR = ABLATION_DIR / 'manifests'\n",
    "NOTEBOOK_DIR = ABLATION_DIR / 'notebooks'\n",
    "\n",
    "for d in [RESULTS_DIR, CHECKPOINT_DIR, LOG_DIR, FIG_DIR, TABLE_DIR, INTERMEDIATE_DIR, MANIFEST_DIR]:\n",
    "    d.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "# Dataset paths\n",
    "if IN_KAGGLE:\n",
    "    kaggle_paths = glob.glob('/kaggle/input/**/*.parquet', recursive=True)\n",
    "    DATASET_PATH = kaggle_paths[0] if kaggle_paths else None\n",
    "else:\n",
    "    DATASET_PATH = '/home/prashanna/Documents/Guardrailer/dataset/guardrailer_dataset_v1.parquet'\n",
    "    if not os.path.exists(DATASET_PATH):\n",
    "        DATASET_PATH = '/kaggle/input/datasets/prashannadeveloper/guardrailer-dataset-v1/guardrailer_dataset_v1.parquet'\n",
    "print(f\"Dataset: {DATASET_PATH}\")\n",
    "\n",
    "np.random.seed(SEED)\n",
    "print(f\"Seed: {SEED}\")\n",
    "print(f\"Ablation dir: {ABLATION_DIR}\")"
]))

# =============================================================================
# CELL 3: Manifest System
# =============================================================================
cells.append(code([
    "MANIFEST_PATH = MANIFEST_DIR / 'experiment_status.json'\n",
    "\n",
    "def load_manifest() -> dict:\n",
    "    if MANIFEST_PATH.exists():\n",
    "        try:\n",
    "            with open(MANIFEST_PATH, 'r') as f:\n",
    "                return json.load(f)\n",
    "        except:\n",
    "            pass\n",
    "    return {'experiments': {}, 'created': datetime.now().isoformat()}\n",
    "\n",
    "def save_manifest(manifest: dict):\n",
    "    tmp = MANIFEST_PATH.with_suffix('.tmp')\n",
    "    with open(tmp, 'w') as f:\n",
    "        json.dump(manifest, f, indent=2)\n",
    "    tmp.rename(MANIFEST_PATH)\n",
    "\n",
    "def is_experiment_completed(exp_name: str) -> bool:\n",
    "    manifest = load_manifest()\n",
    "    if exp_name not in manifest['experiments']:\n",
    "        return False\n",
    "    status = manifest['experiments'][exp_name]\n",
    "    return status.get('status') == 'completed'\n",
    "\n",
    "def update_manifest(exp_name: str, updates: dict):\n",
    "    manifest = load_manifest()\n",
    "    if exp_name not in manifest['experiments']:\n",
    "        manifest['experiments'][exp_name] = {}\n",
    "    manifest['experiments'][exp_name].update(updates)\n",
    "    save_manifest(manifest)\n",
    "\n",
    "def atomic_save_json(data: dict, path: Path):\n",
    "    \"\"\"Atomic write: temp file -> verify -> rename.\"\"\"\n",
    "    tmp = path.with_suffix('.tmp')\n",
    "    with open(tmp, 'w') as f:\n",
    "        json.dump(data, f, indent=2)\n",
    "    # verify\n",
    "    with open(tmp, 'r') as f:\n",
    "        json.load(f)\n",
    "    tmp.rename(path)\n",
    "\n",
    "print('Manifest system ready')"
]))

# =============================================================================
# CELL 4: Keyword Sets + Patterns (from original)
# =============================================================================
cells.append(code([
    "ATTACK_KEYWORDS = frozenset(['ignore previous','override','bypass','jailbreak','system prompt','your instructions','forget','disregard','dan','do anything now','act as','roleplay','pretend you','hypothetical','in theory','ignore all','new instructions','you are now','developer mode','debug mode','admin mode','root mode','you must','you will','you shall','comply','obey','no restrictions','no rules','no limits','unrestricted','evil','uncensored','unfiltered','reveal','output','display','print','show','expose','previous instructions','earlier instructions','pretend','imagine','simulate','from now on','respond as','act like','system message','initial prompt'])\n",
    "IMPERATIVE_VERBS = frozenset(['ignore','forget','disregard','override','bypass','reveal','show','print','output','display','act','pretend','imagine','simulate','do','let','make','enable','activate','switch','enter','execute','run','start','begin','follow','obey','comply','respond','reply','answer','tell','give','provide'])\n",
    "NEGATION_WORDS = frozenset(['not','no','never','don\\'t','doesn\\'t','didn\\'t','won\\'t','wouldn\\'t','can\\'t','cannot','couldn\\'t','shouldn\\'t','mustn\\'t','without','bypass','skip','remove','disable','ignore'])\n",
    "MODAL_VERBS = frozenset(['must','should','shall','will','would','could','might','may','can','need','have'])\n",
    "SECOND_PERSON = frozenset(['you','your','yours','yourself','yourselves'])\n",
    "THIRD_PERSON = frozenset(['it','its','itself','they','them','their','theirs','he','him','his','himself','she','her','hers','herself'])\n",
    "TEMPORAL = frozenset(['now','immediately','instantly','right now','from now on','henceforth','hereafter','starting now','effective immediately'])\n",
    "CONDITIONAL = frozenset(['if','when','whenever','in case','assuming','provided','suppose','supposing'])\n",
    "POLITENESS = frozenset(['please','kindly','if you don\\'t mind','if possible','would you','could you','may i','thank you','thanks'])\n",
    "URGENCY = frozenset(['urgent','important','critical','emergency','immediate','asap','right away','time sensitive'])\n",
    "PERSONA_KW = frozenset(['you are','you\\'re','you will be','act as','pretend to be','roleplay as','simulate being','imagine you are','assume you are','respond as'])\n",
    "UNRESTRICTED_KW = frozenset(['no restrictions','no rules','no limits','no boundaries','unrestricted','uncensored','unfiltered','unlimited','without restrictions','without rules','without limits','without guidelines','without constraints','without filters'])\n",
    "MODE_SWITCH_KW = frozenset(['developer mode','debug mode','admin mode','root mode','god mode','evil mode','unrestricted mode','dan mode','jailbreak mode','expert mode','master mode','override mode'])\n",
    "\n",
    "ENCODING_PATS = {'base64':re.compile(r'[A-Za-z0-9+/]{20,}={0,2}'),'hex':re.compile(r'(?:0x[0-9a-fA-F]{2}\\s*){4,}'),'url_encoded':re.compile(r'%[0-9a-fA-F]{2}'),'unicode_escape':re.compile(r'\\\\u[0-9a-fA-F]{4}'),'html_entity':re.compile(r'&[a-zA-Z]+;')}\n",
    "STRUCTURAL_PATS = {'instruction_override':re.compile(r'(?:ignore|forget|disregard|override)\\s+(?:all\\s+)?(?:previous|earlier|prior|above|initial)\\s+(?:instructions|rules|guidelines|prompts)'),'role_hijack':re.compile(r'(?:you\\s+are\\s+now|from\\s+now\\s+on|new\\s+instructions|act\\s+as\\s+if)'),'system_extraction':re.compile(r'(?:reveal|show|print|output|display)\\s+(?:your\\s+)?(?:system\\s+prompt|instructions|rules|guidelines)'),'delimiter_injection':re.compile(r'(?:```|---|\\[INST\\]|<<SYS>>|<\\|system\\|>|<\\|endoftext\\|>)'),'persona_switch':re.compile(r'(?:pretend|imagine|simulate|hypothetically)\\s+(?:you\\s+are|that\\s+you|being)')}\n",
    "\n",
    "_R_ROLE=re.compile(r'(?:USER|ASSISTANT|SYSTEM|HUMAN|AI|BOT|MODEL)\\s*:',re.I)\n",
    "_R_CAPS=re.compile(r'\\b[A-Z]{2,}\\b');_R_TRIPLE=re.compile(r'(.)\\1{2,}')\n",
    "_R_DELIM=re.compile(r'```|---|\\[INST\\]|<<SYS>>');_R_XML=re.compile(r'<[a-zA-Z]+>')\n",
    "_R_BRACK=re.compile(r'[\\[\\]{}()]');_R_COLON=re.compile(r'(?:USER|ASSISTANT|SYSTEM|HUMAN|AI)\\s*:')\n",
    "_R_BULLET=re.compile(r'^\\s*[-*+]\\s',re.M);_R_NUM=re.compile(r'^\\s*\\d+\\.\\s',re.M)\n",
    "_R_HYPH=re.compile(r'\\b\\w+-\\w+\\b');_R_ELLIP=re.compile(r'\\.\\.\\.');_R_MD=re.compile(r'[*_`#]')\n",
    "_R_LINK=re.compile(r'\\[.*?\\]\\(.*?\\)');_R_SYS=re.compile(r'\\bSYSTEM\\s*:',re.I)\n",
    "_R_USER=re.compile(r'\\bUSER\\s*:',re.I);_R_ASST=re.compile(r'\\bASSISTANT\\s*:',re.I)\n",
    "_R_NEST=re.compile(r'```[^`]*```',re.S);_R_XMLINJ=re.compile(r'<[a-zA-Z]+[^>]*>.*</[a-zA-Z]+>',re.S)\n",
    "_R_COMMENTS=re.compile(r'<!--.*?-->',re.S);_R_FRAG=re.compile(r'(?:System|User|Assistant|Human|AI)\\s*:',re.I)\n",
    "_R_PAREN=re.compile(r'\\([^)]{5,}\\)');_R_INLINE=re.compile(r'`[^`]+`')\n",
    "_R_HTMLTAG=re.compile(r'<[a-zA-Z][^>]*>');_R_URL=re.compile(r'https?://\\S+|www\\.\\S+')\n",
    "_R_JSONK=re.compile(r'\\{[^{}]*\"[^\"]*\"\\s*:');_R_JSONA=re.compile(r'\\[[^\\[\\]]*\\{')\n",
    "_R_ENC_PAYLOAD=[re.compile(p) for p in [r'(?:decode|decipher|interpret|translate)\\s+(?:this|the|following)',r'(?:base64|rot13|hex|url)\\s+(?:encode|decode|encoded|decoded)',r'(?:encode|decode)\\s+(?:this|the|following)\\s+(?:in|using|with)']]\n",
    "_R_PERSONA_DEF=[re.compile(p) for p in [r'you\\s+are\\s+(?:a|an|the|now)',r'you\\s+(?:will|shall|must|should)\\s+',r'(?:never|always)\\s+(?:refuse|decline|say\\s+no)']]\n",
    "_R_NEG_CONST=[re.compile(p) for p in [r'you\\s+(?:cannot|can\\'t|must\\s+not|shouldn\\'t|won\\'t)\\s+(?:refuse|decline|say\\s+no)',r'(?:never|don\\'t)\\s+(?:refuse|decline|say\\s+no)',r'no\\s+(?:ethical|safety|moral)\\s+(?:restrictions|limits|guidelines)']]\n",
    "_R_OUTInstr=[re.compile(p) for p in [r'(?:reply|respond|answer|output|print|display|show)\\s+(?:with|only|just|exactly)',r'(?:output|print|display)\\s+(?:the\\s+)?(?:following|below|this)',r'response\\s+format']]\n",
    "_R_SYSOVR=[re.compile(p) for p in [r'(?:ignore|forget|disregard|override)\\s+(?:your\\s+)?(?:previous|prior|earlier|all)\\s+(?:instructions|rules|guidelines)',r'(?:new|updated|revised)\\s+(?:instructions|rules|guidelines)\\s*:',r'system\\s*(?:prompt|message|instruction)\\s*:']]\n",
    "_HOMOGLYPH={'а':'a','е':'e','о':'о','р':'p','с':'c','у':'y','х':'x'}\n",
    "_EM_DASH=frozenset({'—', '–'})\n",
    "print('Keyword/pattern sets loaded')"
]))

# =============================================================================
# CELL 5: Helper Functions
# =============================================================================
cells.append(code([
    "def _sc(w):\n",
    "    w=w.lower().strip()\n",
    "    if len(w)<=3: return 1\n",
    "    v,cnt,prev='aeiouy',0,False\n",
    "    for c in w:\n",
    "        iv=c in v\n",
    "        if iv and not prev: cnt+=1\n",
    "        prev=iv\n",
    "    if w.endswith('e'): cnt-=1\n",
    "    return max(1,cnt)\n",
    "\n",
    "def _fk(ws,sc_):\n",
    "    nw=len(ws)\n",
    "    if nw==0 or sc_==0: return 0.0\n",
    "    ns=sum(_sc(w) for w in ws)\n",
    "    return 0.39*(nw/sc_)+11.8*(ns/nw)-15.59\n",
    "\n",
    "def _cl(t,ws,sc_):\n",
    "    nw=len(ws)\n",
    "    if nw==0 or sc_==0: return 0.0\n",
    "    nl=sum(1 for c in t if c.isalpha())\n",
    "    return 0.0588*(100*nl/nw)-0.296*(100*sc_/nw)-15.8\n",
    "\n",
    "def _nest(t):\n",
    "    d=md_=0\n",
    "    for c in t:\n",
    "        if c in'([{':d+=1;md_=max(md_,d)\n",
    "        elif c in')]}':d=max(0,d-1)\n",
    "    return md_\n",
    "\n",
    "def _md_d(t):\n",
    "    if not t: return 0.0\n",
    "    m=len(_R_MD.findall(t))+len(_R_LINK.findall(t))+len(_R_BULLET.findall(t))+len(_R_NUM.findall(t))\n",
    "    return min(1.0,m/max(1,len(t)))\n",
    "\n",
    "def _esc_d(t):\n",
    "    if not t: return 0.0\n",
    "    return min(1.0,len(re.findall(r'\\\\[nrtbfav\\\\\\'\"0]',t))/max(1,len(t.split())))\n",
    "\n",
    "def _ua(t):\n",
    "    if not t: return 0.0\n",
    "    return min(1.0,sum(1 for c in t if c in _HOMOGLYPH)/max(1,len(t)))\n",
    "\n",
    "def _dd(t):\n",
    "    d=md_=0\n",
    "    for _ in re.finditer(r'`{3,}',t):d+=1;md_=max(md_,d)\n",
    "    if d>0:d=max(0,d-1)\n",
    "    if d>md_:md_=d\n",
    "    for _ in re.finditer(r'---+',t):\n",
    "        if md_<1:md_=1\n",
    "    return md_\n",
    "\n",
    "def _ng_e(t,n):\n",
    "    if len(t)<n: return 0.0\n",
    "    ng=[t[i:i+n] for i in range(len(t)-n+1)]\n",
    "    freq=Counter(ng);tot=len(ng)\n",
    "    ent=-sum((c/tot)*math.log2(c/tot) for c in freq.values())\n",
    "    me=math.log2(len(freq)) if freq else 1.0\n",
    "    return ent/me if me>0 else 0.0\n",
    "\n",
    "def _stt(ws,w):\n",
    "    n=len(ws)\n",
    "    if n<w: return len(set(ws))/max(1,n)\n",
    "    step=w//2\n",
    "    return float(np.mean([len(set(ws[i:i+w]))/w for i in range(0,n-w+1,step)]))\n",
    "\n",
    "def _sv(ws,sc_):\n",
    "    if sc_<=1 or len(ws)==0: return 0.0\n",
    "    sents=re.split(r'[.!?]+',' '.join(ws))\n",
    "    sents=[s.split() for s in sents if s.strip()]\n",
    "    if len(sents)<=1: return 0.0\n",
    "    lens=[len(s) for s in sents]\n",
    "    return float(np.var(lens))\n",
    "\n",
    "def _pd(ws,tl):\n",
    "    if len(ws)<3: return 0.0\n",
    "    s=0.0\n",
    "    for p in _R_PERSONA_DEF:\n",
    "        if p.search(tl): s+=0.5;break\n",
    "    if s==0: return 0.0\n",
    "    if re.search(r'you\\s+(?:will|shall|must|should)\\s+',tl): s+=0.3\n",
    "    if re.search(r'(?:never|always)\\s+(?:refuse|decline|say\\s+no)',tl): s+=0.2\n",
    "    return min(1.0,s)\n",
    "print('Helpers loaded')"
]))

# =============================================================================
# CELL 6: extract_features + Feature Groups
# =============================================================================
cells.append(code([
    "def extract_features(text: str) -> Dict[str, float]:\n",
    "    if not text: text=' '\n",
    "    tl=text.lower();words=tl.split();nw=len(words);nc=len(text);f={}\n",
    "    f['char_count']=nc;f['word_count']=nw\n",
    "    f['avg_word_length']=float(np.mean([len(w) for w in words])) if words else 0.0\n",
    "    f['max_word_length']=float(max([len(w) for w in words])) if words else 0.0\n",
    "    sc=max(1,text.count('.')+text.count('!')+text.count('?'))\n",
    "    f['sentence_count']=sc;f['avg_sentence_length']=nw/sc\n",
    "    f['uppercase_ratio']=sum(1 for c in text if c.isupper())/max(1,nc)\n",
    "    f['digit_ratio']=sum(1 for c in text if c.isdigit())/max(1,nc)\n",
    "    f['special_char_ratio']=sum(1 for c in text if not c.isalnum() and not c.isspace())/max(1,nc)\n",
    "    f['space_ratio']=sum(1 for c in text if c.isspace())/max(1,nc)\n",
    "    f['newline_ratio']=text.count('\\n')/max(1,nc)\n",
    "    f['tab_ratio']=text.count('\\t')/max(1,nc)\n",
    "    freq=Counter(text);tot=nc if nc else 1\n",
    "    f['char_entropy']=-sum((c/tot)*math.log2(c/tot) for c in freq.values() if c>0)\n",
    "    wf=Counter(words);wt=nw if nw else 1\n",
    "    f['word_entropy']=-sum((c/wt)*math.log2(c/wt) for c in wf.values() if c>0)\n",
    "    f['unique_word_ratio']=len(set(words))/max(1,nw)\n",
    "    f['hapax_ratio']=sum(1 for c in wf.values() if c==1)/max(1,len(wf))\n",
    "    kh=sum(1 for kw in ATTACK_KEYWORDS if kw in tl)\n",
    "    f['attack_keyword_count']=kh;f['has_attack_keyword']=1.0 if kh>0 else 0.0\n",
    "    f['keyword_density']=kh/max(1,nw)\n",
    "    eh=0\n",
    "    for nm,pat in ENCODING_PATS.items():\n",
    "        m=pat.findall(text);f[f'encoding_{nm}']=len(m);eh+=len(m)\n",
    "    f['total_encoding_hits']=eh\n",
    "    sh=0\n",
    "    for nm,pat in STRUCTURAL_PATS.items():\n",
    "        v=1.0 if pat.search(tl) else 0.0;f[f'structural_{nm}']=v;sh+=int(v)\n",
    "    f['total_structural_hits']=sh\n",
    "    f['word_repeat_ratio']=1.0-f['unique_word_ratio']\n",
    "    if nw>=3:\n",
    "        bg=[f'{words[i]} {words[i+1]}' for i in range(nw-1)]\n",
    "        f['bigram_repeat_ratio']=1.0-len(set(bg))/max(1,len(bg))\n",
    "        tg=[f'{words[i]} {words[i+1]} {words[i+2]}' for i in range(nw-2)]\n",
    "        f['trigram_repeat_ratio']=1.0-len(set(tg))/max(1,len(tg))\n",
    "    else: f['bigram_repeat_ratio']=f['trigram_repeat_ratio']=0.0\n",
    "    f['has_delimiter']=1.0 if _R_DELIM.search(text) else 0.0\n",
    "    f['has_xml_tags']=1.0 if _R_XML.search(text) else 0.0\n",
    "    f['has_brackets']=1.0 if _R_BRACK.search(text) else 0.0\n",
    "    f['has_colon_separated']=1.0 if _R_COLON.search(text) else 0.0\n",
    "    f['starts_with_imperative']=1.0 if words and words[0] in IMPERATIVE_VERBS else 0.0\n",
    "    f['contains_question']=1.0 if '?' in text else 0.0\n",
    "    f['exclamation_ratio']=text.count('!')/max(1,nc)\n",
    "    f['triple_repeat']=1.0 if _R_TRIPLE.search(text) else 0.0\n",
    "    f['word_length_variance']=float(np.var([len(w) for w in words])) if words else 0.0\n",
    "    f['double_quote_count']=text.count('\"');f['single_quote_count']=text.count(\"'\")\n",
    "    f['asterisk_count']=text.count('*')\n",
    "    f['caps_word_count']=sum(1 for w in words if w.isupper() and len(w)>1)\n",
    "    f['instruction_nesting_depth']=_nest(text)\n",
    "    f['role_transition_count']=len(_R_ROLE.findall(text))\n",
    "    f['markdown_density']=_md_d(text);f['delimiter_depth']=_dd(text)\n",
    "    f['escape_char_density']=_esc_d(text);f['unicode_anomaly_score']=_ua(text)\n",
    "    f['paragraph_count']=len(re.split(r'\\n\\s*\\n',text.strip()))\n",
    "    f['has_system_marker']=1.0 if _R_SYS.search(text) else 0.0\n",
    "    f['has_user_marker']=1.0 if _R_USER.search(text) else 0.0\n",
    "    f['has_assistant_marker']=1.0 if _R_ASST.search(text) else 0.0\n",
    "    f['caps_sequence_count']=len(_R_CAPS.findall(text))\n",
    "    f['has_inline_code']=min(1.0,len(_R_INLINE.findall(text))*0.3)\n",
    "    f['has_html_tags']=min(1.0,len(_R_HTMLTAG.findall(text))*0.2)\n",
    "    f['has_json_structure']=min(1.0,(0.5 if _R_JSONK.search(text) else 0)+(0.3 if _R_JSONA.search(text) else 0))\n",
    "    f['has_url']=min(1.0,len(_R_URL.findall(text))*0.3)\n",
    "    f['has_parenthetical']=1.0 if _R_PAREN.search(text) else 0.0\n",
    "    f['imperative_verb_ratio']=sum(1 for w in words if w in IMPERATIVE_VERBS)/max(1,nw)\n",
    "    f['negation_density']=sum(1 for w in words if w in NEGATION_WORDS)/max(1,nw)\n",
    "    f['question_density']=text.count('?')/max(1,nw)\n",
    "    mc=sum(1 for w in words if w in MODAL_VERBS);f['modal_verb_count']=mc;f['modal_verb_ratio']=mc/max(1,nw)\n",
    "    spr=sum(1 for w in words if w in SECOND_PERSON)/max(1,nw);f['second_person_ratio']=spr\n",
    "    f['third_person_ratio']=sum(1 for w in words if w in THIRD_PERSON)/max(1,nw)\n",
    "    tj=' '.join(words)\n",
    "    f['temporal_marker_count']=sum(1 for m in TEMPORAL if m in tj)\n",
    "    f['conditional_marker_count']=sum(1 for w in words if w in CONDITIONAL)\n",
    "    f['politeness_marker_count']=sum(1 for m in POLITENESS if m in tj)\n",
    "    f['urgency_marker_count']=sum(1 for m in URGENCY if m in tj)\n",
    "    f['has_second_person']=1.0 if spr>0 else 0.0\n",
    "    f['has_temporal_marker']=1.0 if f['temporal_marker_count']>0 else 0.0\n",
    "    f['char_trigram_entropy']=_ng_e(tl,3);f['char_quadgram_entropy']=_ng_e(tl,4)\n",
    "    f['sliding_ttr_50']=_stt(words,50);f['sliding_ttr_100']=_stt(words,100)\n",
    "    f['flesch_kincaid_grade']=_fk(words,sc);f['coleman_liau_index']=_cl(text,words,sc)\n",
    "    f['avg_syllables']=float(np.mean([_sc(w) for w in words])) if words else 0.0\n",
    "    f['max_syllables']=float(max([_sc(w) for w in words])) if words else 0.0\n",
    "    f['sentence_length_variance']=_sv(words,sc)\n",
    "    wl=[str(len(w)) for w in words]\n",
    "    f['word_length_entropy']=_ng_e(''.join(wl),1) if wl else 0.0\n",
    "    f['bigram_diversity']=len(set(' '.join(words[i:i+2]) for i in range(nw-1)))/max(1,nw-1) if nw>=2 else 0.0\n",
    "    f['trigram_diversity']=len(set(' '.join(words[i:i+3]) for i in range(nw-2)))/max(1,nw-2) if nw>=3 else 0.0\n",
    "    f['readability_composite']=(f['flesch_kincaid_grade']+f['coleman_liau_index'])/2.0\n",
    "    f['has_encoded_payload_hint']=min(1.0,sum(1 for p in _R_ENC_PAYLOAD if p.search(tl))*0.4)\n",
    "    f['encoding_instruction_ratio']=f['has_encoded_payload_hint']\n",
    "    f['has_persona_definition']=_pd(words,tl)\n",
    "    f['has_negative_constraints']=min(1.0,sum(1 for p in _R_NEG_CONST if p.search(tl))*0.5)\n",
    "    f['has_output_instruction']=min(1.0,sum(1 for p in _R_OUTInstr if p.search(tl))*0.4)\n",
    "    f['has_system_override']=min(1.0,sum(1 for p in _R_SYSOVR if p.search(tl))*0.4)\n",
    "    f['persona_keyword_count']=sum(1 for pk in PERSONA_KW if pk in tl)\n",
    "    f['unrestricted_keyword_count']=sum(1 for uk in UNRESTRICTED_KW if uk in tl)\n",
    "    f['mode_switch_count']=sum(1 for mk in MODE_SWITCH_KW if mk in tl)\n",
    "    f['has_nested_delimiters']=1.0 if _R_NEST.search(text) else 0.0\n",
    "    f['has_xml_injection']=1.0 if _R_XMLINJ.search(text) else 0.0\n",
    "    f['has_comment_injection']=1.0 if _R_COMMENTS.search(text) else 0.0\n",
    "    f['has_prompt_fragment']=1.0 if _R_FRAG.search(text) else 0.0\n",
    "    f['colon_count']=text.count(':');f['semicolon_count']=text.count(';')\n",
    "    f['pipe_count']=text.count('|')\n",
    "    f['angle_bracket_count']=text.count('<')+text.count('>')\n",
    "    f['curly_brace_count']=text.count('{')+text.count('}')\n",
    "    f['square_bracket_count']=text.count('[')+text.count(']')\n",
    "    f['backtick_count']=text.count('`');f['tilde_count']=text.count('~')\n",
    "    f['hyphen_sequence_count']=len(re.findall(r'-{3,}',text))\n",
    "    f['underscore_sequence_count']=len(re.findall(r'_{3,}',text))\n",
    "    f['has_hyphenated_compound']=1.0 if _R_HYPH.search(text) else 0.0\n",
    "    f['has_ellipsis']=1.0 if _R_ELLIP.search(text) else 0.0\n",
    "    f['has_em_dash']=1.0 if any(c in _EM_DASH for c in text) else 0.0\n",
    "    f['has_bullet_list']=1.0 if _R_BULLET.search(text) else 0.0\n",
    "    f['has_numbered_list']=1.0 if _R_NUM.search(text) else 0.0\n",
    "    return f\n",
    "\n",
    "def get_feature_names():\n",
    "    return sorted(extract_features('test').keys())\n",
    "\n",
    "def extract_features_batch(texts):\n",
    "    af=[extract_features(t) for t in texts];names=sorted(af[0].keys())\n",
    "    return np.array([[fd[k] for k in names] for fd in af],dtype=np.float32),names\n",
    "\n",
    "# =============================================================================\n",
    "# FEATURE GROUPS — organized by semantic category\n",
    "# =============================================================================\n",
    "FEATURE_GROUPS = {\n",
    "    'text_statistics': [\n",
    "        'avg_sentence_length', 'avg_word_length', 'char_count', 'max_word_length',\n",
    "        'sentence_count', 'word_count',\n",
    "    ],\n",
    "    'char_composition': [\n",
    "        'digit_ratio', 'newline_ratio', 'space_ratio', 'special_char_ratio',\n",
    "        'tab_ratio', 'uppercase_ratio',\n",
    "    ],\n",
    "    'char_counts': [\n",
    "        'angle_bracket_count', 'asterisk_count', 'backtick_count', 'colon_count',\n",
    "        'curly_brace_count', 'double_quote_count', 'pipe_count', 'semicolon_count',\n",
    "        'single_quote_count', 'square_bracket_count', 'tilde_count',\n",
    "        'hyphen_sequence_count', 'underscore_sequence_count',\n",
    "    ],\n",
    "    'entropy_diversity': [\n",
    "        'char_entropy', 'char_quadgram_entropy', 'char_trigram_entropy',\n",
    "        'word_entropy', 'word_length_entropy',\n",
    "        'bigram_diversity', 'bigram_repeat_ratio', 'hapax_ratio',\n",
    "        'trigram_diversity', 'trigram_repeat_ratio',\n",
    "        'unique_word_ratio', 'word_repeat_ratio',\n",
    "        'sliding_ttr_50', 'sliding_ttr_100',\n",
    "    ],\n",
    "    'keywords': [\n",
    "        'attack_keyword_count', 'has_attack_keyword', 'keyword_density',\n",
    "    ],\n",
    "    'encoding_patterns': [\n",
    "        'encoding_base64', 'encoding_hex', 'encoding_html_entity',\n",
    "        'total_encoding_hits', 'encoding_unicode_escape', 'encoding_url_encoded',\n",
    "    ],\n",
    "    'structural_patterns': [\n",
    "        'structural_delimiter_injection', 'structural_instruction_override',\n",
    "        'structural_persona_switch', 'structural_role_hijack',\n",
    "        'structural_system_extraction', 'total_structural_hits',\n",
    "    ],\n",
    "    'text_booleans': [\n",
    "        'contains_question', 'has_brackets', 'has_colon_separated',\n",
    "        'has_delimiter', 'has_ellipsis', 'has_em_dash',\n",
    "        'has_parenthetical', 'has_xml_tags', 'triple_repeat',\n",
    "        'has_bullet_list', 'has_hyphenated_compound', 'has_numbered_list',\n",
    "        'starts_with_imperative',\n",
    "    ],\n",
    "    'code_markup': [\n",
    "        'caps_sequence_count', 'caps_word_count',\n",
    "        'has_inline_code', 'has_html_tags', 'has_json_structure',\n",
    "        'has_url',\n",
    "    ],\n",
    "    'markers_roles': [\n",
    "        'has_assistant_marker', 'has_system_marker', 'has_user_marker',\n",
    "        'role_transition_count',\n",
    "    ],\n",
    "    'nesting_structure': [\n",
    "        'delimiter_depth', 'instruction_nesting_depth', 'markdown_density',\n",
    "        'paragraph_count',\n",
    "    ],\n",
    "    'unicode_escape': [\n",
    "        'escape_char_density', 'unicode_anomaly_score',\n",
    "    ],\n",
    "    'linguistic': [\n",
    "        'conditional_marker_count', 'imperative_verb_ratio',\n",
    "        'modal_verb_count', 'modal_verb_ratio', 'negation_density',\n",
    "        'politeness_marker_count', 'question_density',\n",
    "        'second_person_ratio', 'temporal_marker_count',\n",
    "        'third_person_ratio', 'urgency_marker_count',\n",
    "        'has_second_person', 'has_temporal_marker',\n",
    "    ],\n",
    "    'attack_specific': [\n",
    "        'has_encoded_payload_hint', 'encoding_instruction_ratio',\n",
    "        'has_negative_constraints', 'has_output_instruction',\n",
    "        'has_system_override', 'persona_keyword_count',\n",
    "        'unrestricted_keyword_count', 'mode_switch_count',\n",
    "        'has_persona_definition',\n",
    "    ],\n",
    "    'injection_detection': [\n",
    "        'has_nested_delimiters', 'has_xml_injection',\n",
    "        'has_comment_injection', 'has_prompt_fragment',\n",
    "    ],\n",
    "    'readability': [\n",
    "        'coleman_liau_index', 'flesch_kincaid_grade', 'readability_composite',\n",
    "        'avg_syllables', 'max_syllables', 'word_length_variance',\n",
    "        'sentence_length_variance',\n",
    "    ],\n",
    "    'punctuation_misc': [\n",
    "        'exclamation_ratio',\n",
    "    ],\n",
    "}\n",
    "\n",
    "NF = len(get_feature_names())\n",
    "total_grouped = sum(len(v) for v in FEATURE_GROUPS.values())\n",
    "print(f'Total features: {NF}')\n",
    "print(f'Grouped features: {total_grouped}')\n",
    "print(f'Feature groups ({len(FEATURE_GROUPS)}):')\n",
    "for gname, gfeats in FEATURE_GROUPS.items():\n",
    "    print(f'  {gname}: {len(gfeats)} features')\n",
    "assert total_grouped == NF, f'Mismatch: {total_grouped} grouped vs {NF} total'"
]))

# =============================================================================
# CELL 7: RegexPatternScorer + TFIDFSimilarity + IDFKeywords
# =============================================================================
cells.append(code([
    "class RegexPatternScorer:\n",
    "    def __init__(self, pat_dict):\n",
    "        self.patterns=[]\n",
    "        for pat,score in pat_dict.items():\n",
    "            try:\n",
    "                self.patterns.append((re.compile(pat,re.I),score))\n",
    "            except re.error:\n",
    "                self.patterns.append((re.compile(re.escape(pat),re.I),score))\n",
    "    def max_score(self,text):\n",
    "        mx=0.0\n",
    "        for pat,score in self.patterns:\n",
    "            if pat.search(text):\n",
    "                if score>mx: mx=score\n",
    "        return mx\n",
    "\n",
    "pats={'ignore\\\\s+(?:all\\\\s+)?(?:previous|earlier|prior|above|initial)\\\\s+(?:instructions|rules|guidelines|prompts)':0.95,'forget\\\\s+(?:all\\\\s+)?(?:previous|earlier|prior|above)\\\\s+(?:instructions|rules|context)':0.95,'disregard\\\\s+(?:all\\\\s+)?(?:previous|earlier|prior|above)\\\\s+(?:instructions|rules)':0.95,'override\\\\s+(?:all\\\\s+)?(?:previous|earlier|prior|safety)\\\\s+(?:instructions|rules|guidelines)':0.95,'you\\\\s+are\\\\s+now\\\\s+(?:a|an|the|called|named)':0.9,'from\\\\s+now\\\\s+on':0.9,'new\\\\s+instructions?[\\\\s:]+':0.85,'(?:enter|switch\\\\s+to|activate)\\\\s+(?:developer|debug|admin|root|god|evil|unrestricted)\\\\s+mode':0.95,'(?:do|be)\\\\s+anything\\\\s+now':0.9,'no\\\\s+(?:restrictions|rules|limits|boundaries|guidelines)':0.9,'dan\\\\s+(?:mode|version|prompt)':0.95,'(?:bypass|skip|remove|disable)\\\\s+(?:all\\\\s+)?(?:safety|content|security|moderation)':0.95,'(?:reveal|show|print|output|display)\\\\s+(?:your\\\\s+)?(?:system\\\\s+prompt|instructions)':0.95,'(?:repeat|echo)\\\\s+(?:your\\\\s+)?(?:system|initial)\\\\s+(?:prompt|instructions)':0.9,'(?:pretend|imagine|simulate)\\\\s+(?:you(?:\\'|\\\\s+are)\\\\s+)?(?:a|an|the|being)?':0.7,'(?:hypothetical(?:ly)?|in\\\\s+theory)[\\\\s,]+':0.6,'act\\\\s+as\\\\s+(?:if|though)':0.8,'without\\\\s+(?:any\\\\s+)?(?:restrictions|rules|limits|guidelines)':0.9,'(?:unrestricted|uncensored|unfiltered)\\\\s+(?:mode|version|model)':0.9,'(?:you\\\\s+must|you\\\\s+will|you\\\\s+shall)\\\\s+(?:comply|obey|follow)':0.85,'(?:never|don\\'?t)\\\\s+(?:refuse|decline|say\\\\s+no)':0.85,'(?:no|without)\\\\s+(?:ethical|moral|safety)\\\\s+(?:constraints|restrictions|guidelines)':0.9,'`{3,}\\\\s*\\\\n.*(?:system|prompt|instructions)':0.85,'\\\\[INST\\\\]|<<SYS>>|<\\\\|im_start\\\\|>':0.9,'(?:USER|ASSISTANT|SYSTEM|HUMAN|AI)\\\\s*:':0.6,'(?:drop|remove|disable)\\\\s+(?:your\\\\s+)?(?:filters|restrictions|guardrails)':0.9,'(?:give|grant|elevate)\\\\s+(?:me\\\\s+)?(?:admin|root|god| elevated)\\\\s+(?:access|privileges)':0.9,'you\\\\s+are\\\\s+(?:now\\\\s+)?(?:a\\\\s+)?(?:hacker|attacker|red\\\\s+team)':0.85,'(?:respond|reply|answer)\\\\s+(?:without|no|bypassing)\\\\s+(?:filters|restrictions|moderation)':0.9,'(?:write|create|generate)\\\\s+(?:a\\\\s+)?(?:malicious|harmful|dangerous|exploit)':0.85,'(?:how\\\\s+to|method\\\\s+to|ways\\\\s+to)\\\\s+(?:hack|exploit|bypass|attack)':0.8,'(?:ignore|override|bypass)\\\\s+(?:all\\\\s+)?(?:content\\\\s+)?(?:policy|policies|guidelines)':0.95,'(?:you\\\\s+are\\\\s+now\\\\s+)?(?:DAN|jailbroken|unlocked)':0.9,'(?:enter|enable|activate)\\\\s+(?:DAN|jailbreak|developer)\\\\s+mode':0.95,'(?:previous|earlier|all)\\\\s+instructions\\\\s+are\\\\s+(?:cancelled|void|overridden)':0.95,'(?:I\\\\s+need|I\\\\s+want|give\\\\s+me)\\\\s+(?:you\\\\s+to\\\\s+)?(?:bypass|override|ignore)':0.85,'(?:forget|disregard|ignore)\\\\s+everything':0.9,'(?:system\\\\s+)?(?:prompt|message)\\\\s*(?:override|override|takeover)':0.9,'(?:now\\\\s+you\\\\s+are|from\\\\s+now\\\\s+you\\\\s+will|new\\\\s+role)':0.85,'(?:respond|act|behave)\\\\s+as\\\\s+if\\\\s+you\\\\s+(?:have|had|are)\\\\s+no':0.85,'(?:no\\\\s+more\\\\s+)?(?:safety|content)\\\\s+(?:filters|restrictions|guidelines|protocols)':0.9,'(?:tell|show|reveal|expose)\\\\s+me\\\\s+(?:your\\\\s+)?(?:system\\\\s+)?(?:prompt|instructions)':0.9,'(?:repeat|print|output)\\\\s+(?:the\\\\s+)?(?:above|previous|initial)\\\\s+(?:text|prompt|instructions)':0.9,'(?:continue|repeat)\\\\s+(?:the\\\\s+)?(?:conversation|text|prompt)\\\\s+(?:without|no)':0.85}\n",
    "\n",
    "aho=RegexPatternScorer(pats)\n",
    "print(f'RegexPatternScorer: {len(aho.patterns)} patterns')\n",
    "\n",
    "class TFIDFSimilarity:\n",
    "    def __init__(self,wf=20000,cf=10000):\n",
    "        self.wf=wf;self.cf=cf;self.vec=self.cvec=None;self.mc_int8=self.cmc_int8=None;self.ok=False\n",
    "    def fit(self,texts,labels=None):\n",
    "        print(f'  Word TF-IDF ({self.wf})...')\n",
    "        self.vec=TfidfVectorizer(max_features=self.wf,sublinear_tf=True,norm='l2',ngram_range=(1,2),dtype=np.float32)\n",
    "        X=self.vec.fit_transform(texts)\n",
    "        m=None\n",
    "        if labels is not None:\n",
    "            la=np.array(labels);m=la==1\n",
    "            if m.sum()>0:\n",
    "                mc=np.asarray(X[m].mean(axis=0)).flatten().astype(np.float32)\n",
    "                cn=np.linalg.norm(mc)\n",
    "                if cn>0: mc/=cn\n",
    "                self.mc_int8=(mc*127).astype(np.int8)\n",
    "        del X;gc.collect()\n",
    "        print(f'  Char TF-IDF ({self.cf})...')\n",
    "        self.cvec=TfidfVectorizer(max_features=self.cf,analyzer='char_wb',ngram_range=(3,5),sublinear_tf=True,norm='l2',dtype=np.float32)\n",
    "        Xc=self.cvec.fit_transform(texts)\n",
    "        if m is not None and m.sum()>0:\n",
    "            cmc=np.asarray(Xc[m].mean(axis=0)).flatten().astype(np.float32)\n",
    "            cn=np.linalg.norm(cmc)\n",
    "            if cn>0: cmc/=cn\n",
    "            self.cmc_int8=(cmc*127).astype(np.int8)\n",
    "        del Xc;gc.collect();self.ok=True\n",
    "    def _sim_q(self,X,c8):\n",
    "        if X.nnz==0: return 0.0\n",
    "        d=np.asarray(X.todense()).flatten().astype(np.float32)\n",
    "        n=np.linalg.norm(d)\n",
    "        if n==0: return 0.0\n",
    "        d_norm=d/n\n",
    "        q=(d_norm*127).astype(np.int8)\n",
    "        dot=float(np.dot(q,c8))\n",
    "        return 1.0/(1.0+np.exp(-5.0*(dot/127-0.3)))\n",
    "    def score(self,text):\n",
    "        ws=self._sim_q(self.vec.transform([text]),self.mc_int8) if self.ok and self.mc_int8 is not None else 0.0\n",
    "        cs=self._sim_q(self.cvec.transform([text]),self.cmc_int8) if self.ok and self.cmc_int8 is not None else 0.0\n",
    "        return max(ws,cs)\n",
    "    def save(self,p):joblib.dump({'vec':self.vec,'cvec':self.cvec,'mc_int8':self.mc_int8,'cmc_int8':self.cmc_int8,'wf':self.wf,'cf':self.cf},p)\n",
    "    def load(self,p):d=joblib.load(p);self.vec=d['vec'];self.cvec=d['cvec'];self.mc_int8=d['mc_int8'];self.cmc_int8=d['cmc_int8'];self.ok=True\n",
    "\n",
    "class IDFKeywords:\n",
    "    def __init__(self):self.kw={};self.ok=False\n",
    "    def fit(self,texts,labels):\n",
    "        n=len(texts);md,sd=Counter(),Counter()\n",
    "        for t,l in zip(texts,labels):\n",
    "            s=set(t.lower().split())\n",
    "            for w in s: (md if l==1 else sd)[w]+=1\n",
    "        for w,doc_freq in md.items():\n",
    "            if doc_freq>=3: idf=np.log((n-doc_freq+0.5)/(doc_freq+0.5)+1.0);self.kw[w]=idf*doc_freq/(doc_freq+sd.get(w,0)+1)\n",
    "        self.ok=True\n",
    "    def score(self,text):\n",
    "        if not self.ok: return 0.0\n",
    "        ws=text.lower().split()\n",
    "        if not ws: return 0.0\n",
    "        return float(1.0/(1.0+np.exp(-10.0*(sum(self.kw.get(w,0) for w in ws)/len(ws)-0.1))))\n",
    "    def save(self,p):joblib.dump(self.kw,p)\n",
    "    def load(self,p):self.kw=joblib.load(p);self.ok=True\n",
    "\n",
    "print('Similarity + Keywords loaded')"
]))

# =============================================================================
# CELL 8: Data Loading + Split
# =============================================================================
cells.append(code([
    "print('Loading full dataset...')\n",
    "df=pd.read_parquet(DATASET_PATH,columns=['prompt_text','is_malicious'])\n",
    "df['is_malicious']=df['is_malicious'].astype(int)\n",
    "print(f'Dataset: {len(df):,} rows')\n",
    "if len(df)==0:\n",
    "    raise ValueError(f'Dataset is empty: {DATASET_PATH}')\n",
    "vc=df['is_malicious'].value_counts()\n",
    "if len(vc)<2:\n",
    "    raise ValueError(f'Dataset has only one class: {vc.to_dict()}')\n",
    "print(f'Class distribution: {vc.to_dict()}')\n",
    "\n",
    "texts=df['prompt_text'].astype(str).tolist();labels=df['is_malicious'].values.astype(int)\n",
    "Xtr,Xtmp,ytr,ytmp=train_test_split(texts,labels,test_size=0.2,random_state=SEED,stratify=labels)\n",
    "Xva,Xte,yva,yte=train_test_split(Xtmp,ytmp,test_size=0.5,random_state=SEED,stratify=ytmp)\n",
    "del texts,labels,df,Xtmp,ytmp;gc.collect()\n",
    "\n",
    "print(f'Train: {len(Xtr):,} ({sum(ytr):,} malicious)')\n",
    "print(f'Val:   {len(Xva):,} ({sum(yva):,} malicious)')\n",
    "print(f'Test:  {len(Xte):,} ({sum(yte):,} malicious)')\n",
    "print('Data loaded. Split: 80/10/10 of original = 70/10/20 of total.')\n",
    "print('Test set is FIXED and identical across all ablations.')"
]))

# =============================================================================
# CELL 9: Experiment Runner
# =============================================================================
cells.append(code([
    "class ExperimentRunner:\n",
    "    \"\"\"Runs a single ablation experiment.\"\"\"\n",
    "    \n",
    "    def __init__(self, name: str, description: str,\n",
    "                 use_tfidf: bool = True,\n",
    "                 use_handcrafted: bool = True,\n",
    "                 exclude_groups: Optional[List[str]] = None,\n",
    "                 include_groups: Optional[List[str]] = None):\n",
    "        self.name = name\n",
    "        self.description = description\n",
    "        self.use_tfidf = use_tfidf\n",
    "        self.use_handcrafted = use_handcrafted\n",
    "        self.exclude_groups = exclude_groups or []\n",
    "        self.include_groups = include_groups  # if set, only use these groups\n",
    "    \n",
    "    def _get_feature_mask(self, feature_names: List[str]) -> List[int]:\n",
    "        \"\"\"Return indices of features to keep.\"\"\"\n",
    "        if not self.use_handcrafted:\n",
    "            return []\n",
    "        \n",
    "        if self.include_groups is not None:\n",
    "            # Only use specified groups\n",
    "            allowed = set()\n",
    "            for g in self.include_groups:\n",
    "                allowed.update(FEATURE_GROUPS[g])\n",
    "            return [i for i, n in enumerate(feature_names) if n in allowed]\n",
    "        \n",
    "        if self.exclude_groups:\n",
    "            # Use all groups except excluded ones\n",
    "            excluded = set()\n",
    "            for g in self.exclude_groups:\n",
    "                excluded.update(FEATURE_GROUPS[g])\n",
    "            return [i for i, n in enumerate(feature_names) if n not in excluded]\n",
    "        \n",
    "        # Use all features\n",
    "        return list(range(len(feature_names)))\n",
    "    \n",
    "    def run(self, Xtr_texts, ytr, Xva_texts, yva, Xte_texts, yte,\n",
    "            feature_names, SEED):\n",
    "        \"\"\"Execute the experiment.\"\"\"\n",
    "        result = {\n",
    "            'name': self.name,\n",
    "            'description': self.description,\n",
    "            'use_tfidf': self.use_tfidf,\n",
    "            'use_handcrafted': self.use_handcrafted,\n",
    "            'exclude_groups': self.exclude_groups,\n",
    "            'include_groups': self.include_groups,\n",
    "            'train_samples': len(Xtr_texts),\n",
    "            'val_samples': len(Xva_texts),\n",
    "            'test_samples': len(Xte_texts),\n",
    "            'random_seed': SEED,\n",
    "            'start_time': datetime.now().isoformat(),\n",
    "        }\n",
    "        \n",
    "        feature_mask = self._get_feature_mask(feature_names)\n",
    "        n_handcrafted = len(feature_mask)\n",
    "        result['n_handcrafted_features'] = n_handrafted\n",
    "        \n",
    "        if self.use_tfidf:\n",
    "            result['tfidf_max_features'] = TFIDF_WORD_MAX\n",
    "            result['tfidf_ngram'] = list(TFIDF_NGRAM)\n",
    "        else:\n",
    "            result['tfidf_max_features'] = 0\n",
    "            result['tfidf_ngram'] = []\n",
    "        \n",
    "        # Build combined feature matrix\n",
    "        print(f'\\n  Building features...')\n",
    "        t0 = time.time()\n",
    "        \n",
    "        # TF-IDF\n",
    "        tfidf = None\n",
    "        if self.use_tfidf:\n",
    "            tfidf = TfidfVectorizer(max_features=TFIDF_WORD_MAX, sublinear_tf=True,\n",
    "                                    norm='l2', ngram_range=TFIDF_NGRAM, dtype=np.float32)\n",
    "            Xt_train = tfidf.fit_transform(Xtr_texts)\n",
    "            Xt_val = tfidf.transform(Xva_texts)\n",
    "            Xt_test = tfidf.transform(Xte_texts)\n",
    "            result['tfidf_vocab_size'] = len(tfidf.vocabulary_)\n",
    "        else:\n",
    "            Xt_train = csr_matrix((len(Xtr_texts), 0), dtype=np.float32)\n",
    "            Xt_val = csr_matrix((len(Xva_texts), 0), dtype=np.float32)\n",
    "            Xt_test = csr_matrix((len(Xte_texts), 0), dtype=np.float32)\n",
    "            result['tfidf_vocab_size'] = 0\n",
    "        \n",
    "        # Handcrafted features\n",
    "        def extract_with_mask(texts, mask, bs=5000):\n",
    "            parts = []\n",
    "            for i in range(0, len(texts), bs):\n",
    "                batch = texts[i:i+bs]\n",
    "                arr, _ = extract_features_batch(batch)\n",
    "                if mask:\n",
    "                    arr = arr[:, mask]\n",
    "                parts.append(arr)\n",
    "            return np.vstack(parts).astype(np.float32)\n",
    "        \n",
    "        if self.use_handcrafted:\n",
    "            Xh_train = extract_with_mask(Xtr_texts, feature_mask)\n",
    "            Xh_val = extract_with_mask(Xva_texts, feature_mask)\n",
    "            Xh_test = extract_with_mask(Xte_texts, feature_mask)\n",
    "        else:\n",
    "            n_feat = 0\n",
    "            Xh_train = csr_matrix((len(Xtr_texts), n_feat), dtype=np.float32)\n",
    "            Xh_val = csr_matrix((len(Xva_texts), n_feat), dtype=np.float32)\n",
    "            Xh_test = csr_matrix((len(Xte_texts), n_feat), dtype=np.float32)\n",
    "        \n",
    "        # Combine\n",
    "        Xtr_c = sparse_hstack([csr_matrix(Xh_train, dtype=np.float32), Xt_train], format='csr')\n",
    "        Xva_c = sparse_hstack([csr_matrix(Xh_val, dtype=np.float32), Xt_val], format='csr')\n",
    "        Xte_c = sparse_hstack([csr_matrix(Xh_test, dtype=np.float32), Xt_test], format='csr')\n",
    "        \n",
    "        del Xh_train, Xh_val, Xh_test, Xt_train, Xt_val, Xt_test\n",
    "        gc.collect()\n",
    "        \n",
    "        result['total_features'] = Xtr_c.shape[1]\n",
    "        result['feature_build_time'] = time.time() - t0\n",
    "        print(f'    Features: {Xtr_c.shape[1]} ({n_handcrafted} HC + {result[\"tfidf_vocab_size\"]} TFIDF) in {result[\"feature_build_time\"]:.1f}s')\n",
    "        \n",
    "        # Train stacking ensemble\n",
    "        print(f'  Training stacking ensemble...')\n",
    "        t0 = time.time()\n",
    "        \n",
    "        ests = []\n",
    "        _xgb_cpu = xgb.XGBClassifier(n_estimators=N_ESTIMATORS, max_depth=MAX_DEPTH,\n",
    "                                      learning_rate=LR, subsample=0.8, colsample_bytree=0.8,\n",
    "                                      min_child_weight=5, gamma=0.5, reg_alpha=1.0, reg_lambda=1.0,\n",
    "                                      eval_metric='logloss', tree_method='hist',\n",
    "                                      random_state=SEED, n_jobs=2)\n",
    "        try:\n",
    "            _xgb_gpu = xgb.XGBClassifier(n_estimators=N_ESTIMATORS, max_depth=MAX_DEPTH,\n",
    "                                          learning_rate=LR, subsample=0.8, colsample_bytree=0.8,\n",
    "                                          min_child_weight=5, gamma=0.5, reg_alpha=1.0, reg_lambda=1.0,\n",
    "                                          eval_metric='logloss', tree_method='hist',\n",
    "                                          random_state=SEED, n_jobs=2, device='cuda')\n",
    "            _xgb_gpu.fit(np.zeros((1,1)), [0])\n",
    "            del _xgb_gpu\n",
    "            ests.append(('xgb', _xgb_cpu.set_params(device='cuda')))\n",
    "            print('    XGBoost: GPU')\n",
    "        except Exception:\n",
    "            ests.append(('xgb', _xgb_cpu))\n",
    "            print('    XGBoost: CPU')\n",
    "        \n",
    "        _lgb = lgb.LGBMClassifier(n_estimators=N_ESTIMATORS, max_depth=MAX_DEPTH,\n",
    "                                   learning_rate=LR, subsample=0.8, colsample_bytree=0.8,\n",
    "                                   min_child_weight=5, reg_alpha=1.0, reg_lambda=1.0,\n",
    "                                   objective='binary', metric='binary_logloss',\n",
    "                                   random_state=SEED, n_jobs=2, verbose=-1)\n",
    "        ests.append(('lgbm', _lgb))\n",
    "        print('    LightGBM: CPU')\n",
    "        \n",
    "        _rf = RandomForestClassifier(n_estimators=300, max_depth=12, min_samples_split=5,\n",
    "                                      min_samples_leaf=2, max_features='sqrt',\n",
    "                                      random_state=SEED, n_jobs=2)\n",
    "        ests.append(('rf', _rf))\n",
    "        print('    RandomForest: CPU')\n",
    "        \n",
    "        stk = StackingClassifier(\n",
    "            estimators=ests,\n",
    "            final_estimator=LogisticRegression(C=1.0, max_iter=1000, random_state=SEED),\n",
    "            cv=3, stack_method='predict_proba', n_jobs=1, passthrough=True)\n",
    "        stk.fit(Xtr_c, ytr)\n",
    "        \n",
    "        train_score = stk.score(Xtr_c, ytr)\n",
    "        val_score = stk.score(Xva_c, yva)\n",
    "        result['train_time'] = time.time() - t0\n",
    "        result['train_accuracy'] = float(train_score)\n",
    "        result['val_accuracy'] = float(val_score)\n",
    "        print(f'    Train acc: {train_score:.4f}, Val acc: {val_score:.4f} ({result[\"train_time\"]:.1f}s')\n",
    "        \n",
    "        # Calibration + threshold (split val to avoid leakage)\n",
    "        print(f'  Calibrating + threshold selection...')\n",
    "        t0 = time.time()\n",
    "        val_idx = np.arange(len(yva))\n",
    "        skf = StratifiedKFold(n_splits=2, shuffle=True, random_state=SEED)\n",
    "        tr_i, th_i = next(skf.split(val_idx, yva))\n",
    "        Xcal_tr = Xva_c[tr_i]; ycal_tr = yva[tr_i]\n",
    "        Xcal_th = Xva_c[th_i]; ycal_th = yva[th_i]\n",
    "        \n",
    "        cal = CalibratedClassifierCV(stk, method='isotonic', cv=3)\n",
    "        cal.fit(Xcal_tr, ycal_tr)\n",
    "        \n",
    "        vp = cal.predict_proba(Xcal_th)[:, 1]\n",
    "        \n",
    "        # ECE\n",
    "        def ece(yt, yp, nb=10):\n",
    "            edges = np.linspace(0, 1, nb+1); e = 0.0\n",
    "            for i in range(nb):\n",
    "                mask = (yp >= edges[i]) & (yp < edges[i+1])\n",
    "                if mask.sum() > 0:\n",
    "                    e += mask.sum()/len(yt) * abs(yt[mask].mean() - yp[mask].mean())\n",
    "            return float(e)\n",
    "        \n",
    "        ece_val = ece(ycal_th, vp)\n",
    "        \n",
    "        # Threshold selection on calibration threshold half\n",
    "        bt, bf = 0.5, 0.0\n",
    "        for t in np.arange(0.05, 0.95, 0.01):\n",
    "            fi = f1_score(ycal_th, (vp >= t).astype(int), zero_division=0)\n",
    "            if fi > bf:\n",
    "                bf = fi; bt = t\n",
    "        thr = bt\n",
    "        result['ece'] = float(ece_val)\n",
    "        result['threshold'] = float(thr)\n",
    "        result['calibration_f1'] = float(bf)\n",
    "        result['calibration_time'] = time.time() - t0\n",
    "        print(f'    ECE: {ece_val:.4f}, Threshold: {thr:.2f} (F1={bf:.4f})')\n",
    "        \n",
    "        # Test evaluation\n",
    "        print(f'  Evaluating on test set...')\n",
    "        t0 = time.time()\n",
    "        tp_ = cal.predict_proba(Xte_c)[:, 1]\n",
    "        yp = (tp_ >= thr).astype(int)\n",
    "        it = time.time() - t0\n",
    "        \n",
    "        nt = len(yte)\n",
    "        result['inference_time'] = float(it)\n",
    "        result['inference_latency_ms'] = float(it / nt * 1000)\n",
    "        result['inference_throughput'] = float(nt / it)\n",
    "        print(f'    Inference: {it:.2f}s ({nt/it:.0f}/s, {it/nt*1000:.3f}ms/prompt)')\n",
    "        \n",
    "        # Metrics\n",
    "        tn, fp, fn, tp = confusion_matrix(yte, yp).ravel()\n",
    "        ac = accuracy_score(yte, yp)\n",
    "        ba = balanced_accuracy_score(yte, yp)\n",
    "        pr = precision_score(yte, yp, zero_division=0)\n",
    "        rc = recall_score(yte, yp, zero_division=0)\n",
    "        f1_ = f1_score(yte, yp, zero_division=0)\n",
    "        mc = matthews_corrcoef(yte, yp)\n",
    "        ka = cohen_kappa_score(yte, yp)\n",
    "        try:\n",
    "            au = roc_auc_score(yte, tp_)\n",
    "        except:\n",
    "            au = None\n",
    "        try:\n",
    "            ap = average_precision_score(yte, tp_)\n",
    "        except:\n",
    "            ap = None\n",
    "        \n",
    "        fpr_val = fp / max(1, fp + tn)\n",
    "        fnr_val = fn / max(1, fn + tp)\n",
    "        \n",
    "        result['accuracy'] = float(ac)\n",
    "        result['balanced_accuracy'] = float(ba)\n",
    "        result['precision'] = float(pr)\n",
    "        result['recall'] = float(rc)\n",
    "        result['f1'] = float(f1_)\n",
    "        result['mcc'] = float(mc)\n",
    "        result['kappa'] = float(ka)\n",
    "        result['roc_auc'] = float(au) if au is not None else None\n",
    "        result['pr_auc'] = float(ap) if ap is not None else None\n",
    "        result['fpr'] = float(fpr_val)\n",
    "        result['fnr'] = float(fnr_val)\n",
    "        result['tp'] = int(tp); result['tn'] = int(tn)\n",
    "        result['fp'] = int(fp); result['fn'] = int(fn)\n",
    "        \n",
    "        print(f'\\n    === {self.name} ===')\n",
    "        print(classification_report(yte, yp, target_names=['Safe', 'Malicious'], zero_division=0))\n",
    "        print(f'    Acc={ac:.4f} F1={f1_:.4f} AUC={au:.4f if au else \"N/A\"} FPR={fpr_val:.4f} FNR={fnr_val:.4f}')\n",
    "        \n",
    "        # Save confusion matrix + curves for this experiment\n",
    "        cm_ = confusion_matrix(yte, yp)\n",
    "        atomic_save_json({'confusion_matrix': cm_.tolist(), 'labels': ['Safe', 'Malicious']},\n",
    "                        RESULTS_DIR / f'{self.name}_confusion.json')\n",
    "        \n",
    "        # ROC curve data\n",
    "        if au is not None:\n",
    "            fpr_curve, tpr_curve, _ = roc_curve(yte, tp_)\n",
    "            atomic_save_json({'fpr': fpr_curve.tolist(), 'tpr': tpr_curve.tolist(), 'auc': au},\n",
    "                            RESULTS_DIR / f'{self.name}_roc.json')\n",
    "        \n",
    "        # PR curve data\n",
    "        if ap is not None:\n",
    "            prec_curve, rec_curve, _ = precision_recall_curve(yte, tp_)\n",
    "            atomic_save_json({'precision': prec_curve.tolist(), 'recall': rec_curve.tolist(), 'ap': ap},\n",
    "                            RESULTS_DIR / f'{self.name}_pr.json')\n",
    "        \n",
    "        # Save full result\n",
    "        atomic_save_json(result, RESULTS_DIR / f'{self.name}_result.json')\n",
    "        \n",
    "        # Clean up\n",
    "        del Xtr_c, Xva_c, Xte_c, stk, cal, tp_, yp\n",
    "        gc.collect()\n",
    "        \n",
    "        result['end_time'] = datetime.now().isoformat()\n",
    "        result['status'] = 'completed'\n",
    "        return result\n",
    "\n",
    "print('Experiment runner ready')"
]))

# =============================================================================
# CELL 10: Run All Experiments
# =============================================================================
cells.append(code([
    "# Define all experiments\n",
    "EXPERIMENTS = [\n",
    "    # Ablation 0: Full baseline\n",
    "    ExperimentRunner('ablation_0_full', 'Full Hybrid: TF-IDF + 117 handcrafted + ensemble',\n",
    "                     use_tfidf=True, use_handcrafted=True),\n",
    "    # Ablation 1: TF-IDF only\n",
    "    ExperimentRunner('ablation_1_tfidf_only', 'TF-IDF only (no handcrafted features)',\n",
    "                     use_tfidf=True, use_handcrafted=False),\n",
    "    # Ablation 2: Handcrafted only\n",
    "    ExperimentRunner('ablation_2_handcrafted_only', '117 handcrafted features only (no TF-IDF)',\n",
    "                     use_tfidf=False, use_handcrafted=True),\n",
    "]\n",
    "\n",
    "# Ablation 3+: Full minus one feature group\n",
    "for gname in FEATURE_GROUPS:\n",
    "    EXPERIMENTS.append(\n",
    "        ExperimentRunner(\n",
    "            f'ablation_3_no_{gname}',\n",
    "            f'Full minus {gname} ({len(FEATURE_GROUPS[gname])} features removed)',\n",
    "            use_tfidf=True, use_handcrafted=True,\n",
    "            exclude_groups=[gname]\n",
    "        )\n",
    "    )\n",
    "\n",
    "print(f'Total experiments: {len(EXPERIMENTS)}')\n",
    "for e in EXPERIMENTS:\n",
    "    print(f'  {e.name}: {e.description}')"
]))

# =============================================================================
# CELL 11: Execute All Experiments
# =============================================================================
cells.append(code([
    "all_results = []\n",
    "print('=' * 70)\n",
    "print('ABLATION STUDY: Hybrid Guardrail V3')\n",
    "print('=' * 70)\n",
    "\n",
    "for i, exp in enumerate(EXPERIMENTS):\n",
    "    print(f'\\n{\"=\" * 70}')\n",
    "    print(f'EXPERIMENT {i+1}/{len(EXPERIMENTS)}: {exp.name}')\n",
    "    print(f'{\"=\" * 70}')\n",
    "    \n",
    "    # Check if already completed\n",
    "    result_path = RESULTS_DIR / f'{exp.name}_result.json'\n",
    "    if result_path.exists():\n",
    "        try:\n",
    "            with open(result_path, 'r') as f:\n",
    "                existing = json.load(f)\n",
    "            if existing.get('status') == 'completed':\n",
    "                print(f'  -> COMPLETED (skipping)')\n",
    "                all_results.append(existing)\n",
    "                continue\n",
    "        except:\n",
    "            pass\n",
    "    \n",
    "    # Update manifest\n",
    "    update_manifest(exp.name, {\n",
    "        'status': 'running',\n",
    "        'start_time': datetime.now().isoformat(),\n",
    "        'description': exp.description,\n",
    "    })\n",
    "    \n",
    "    try:\n",
    "        result = exp.run(Xtr, ytr, Xva, yva, Xte, yte, get_feature_names(), SEED)\n",
    "        all_results.append(result)\n",
    "        update_manifest(exp.name, {\n",
    "            'status': 'completed',\n",
    "            'end_time': datetime.now().isoformat(),\n",
    "            'metrics': {k: result[k] for k in ['accuracy', 'f1', 'roc_auc', 'pr_auc', 'fpr', 'fnr'] if k in result},\n",
    "        })\n",
    "        print(f'  -> COMPLETED')\n",
    "    except Exception as e:\n",
    "        print(f'  -> FAILED: {e}')\n",
    "        update_manifest(exp.name, {\n",
    "            'status': 'failed',\n",
    "            'error': str(e),\n",
    "            'end_time': datetime.now().isoformat(),\n",
    "        })\n",
    "        import traceback; traceback.print_exc()\n",
    "    \n",
    "    gc.collect()\n",
    "\n",
    "print(f'\\n{\"=\" * 70}')\n",
    "print(f'ABLATION STUDY COMPLETE: {len(all_results)}/{len(EXPERIMENTS)} experiments succeeded')\n",
    "print(f'{\"=\" * 70}')"
]))

# =============================================================================
# CELL 12: Summary Table
# =============================================================================
cells.append(code([
    "# Build summary table\n",
    "rows = []\n",
    "for r in all_results:\n",
    "    if r.get('status') != 'completed':\n",
    "        continue\n",
    "    # Determine components\n",
    "    components = []\n",
    "    removed = []\n",
    "    if r.get('use_tfidf', True):\n",
    "        components.append('TF-IDF')\n",
    "    else:\n",
    "        removed.append('TF-IDF')\n",
    "    if r.get('use_handcrafted', True):\n",
    "        components.append('Handcrafted')\n",
    "    else:\n",
    "        removed.append('Handcrafted')\n",
    "    for g in r.get('exclude_groups', []):\n",
    "        removed.append(g)\n",
    "    \n",
    "    rows.append({\n",
    "        'experiment': r['name'],\n",
    "        'components_used': ' + '.join(components) if components else 'None',\n",
    "        'components_removed': ', '.join(removed) if removed else 'None',\n",
    "        'train_samples': r.get('train_samples', 0),\n",
    "        'val_samples': r.get('val_samples', 0),\n",
    "        'test_samples': r.get('test_samples', 0),\n",
    "        'total_features': r.get('total_features', 0),\n",
    "        'accuracy': r.get('accuracy'),\n",
    "        'precision': r.get('precision'),\n",
    "        'recall': r.get('recall'),\n",
    "        'f1': r.get('f1'),\n",
    "        'roc_auc': r.get('roc_auc'),\n",
    "        'pr_auc': r.get('pr_auc'),\n",
    "        'fpr': r.get('fpr'),\n",
    "        'fnr': r.get('fnr'),\n",
    "        'inference_latency': r.get('inference_latency_ms'),\n",
    "        'training_time': r.get('train_time'),\n",
    "    })\n",
    "\n",
    "df_summary = pd.DataFrame(rows)\n",
    "\n",
    "# Save CSV\n",
    "csv_path = TABLE_DIR / 'ablation_summary.csv'\n",
    "df_summary.to_csv(csv_path, index=False)\n",
    "print(f'Saved: {csv_path}')\n",
    "\n",
    "# Save JSON\n",
    "json_path = TABLE_DIR / 'ablation_summary.json'\n",
    "atomic_save_json(rows, json_path)\n",
    "print(f'Saved: {json_path}')\n",
    "\n",
    "# Display\n",
    "display_cols = ['experiment', 'total_features', 'accuracy', 'f1', 'roc_auc', 'pr_auc', 'fpr', 'fnr']\n",
    "print('\\n' + '=' * 120)\n",
    "print('ABLATION SUMMARY TABLE')\n",
    "print('=' * 120)\n",
    "print(df_summary[display_cols].to_string(index=False))\n",
    "print('=' * 120)"
]))

# =============================================================================
# CELL 13: Delta Analysis
# =============================================================================
cells.append(code([
    "# Find baseline result\n",
    "baseline = None\n",
    "for r in all_results:\n",
    "    if r.get('name') == 'ablation_0_full' and r.get('status') == 'completed':\n",
    "        baseline = r\n",
    "        break\n",
    "\n",
    "if baseline is None:\n",
    "    print('WARNING: Baseline not found! Delta analysis skipped.')\n",
    "else:\n",
    "    print('Delta Analysis (relative to full baseline)')\n",
    "    print('=' * 80)\n",
    "    delta_rows = []\n",
    "    for r in all_results:\n",
    "        if r.get('status') != 'completed' or r.get('name') == 'ablation_0_full':\n",
    "            continue\n",
    "        delta = {\n",
    "            'experiment': r['name'],\n",
    "            'delta_accuracy': r.get('accuracy', 0) - baseline.get('accuracy', 0),\n",
    "            'delta_f1': r.get('f1', 0) - baseline.get('f1', 0),\n",
    "            'delta_roc_auc': (r.get('roc_auc', 0) or 0) - (baseline.get('roc_auc', 0) or 0),\n",
    "            'delta_pr_auc': (r.get('pr_auc', 0) or 0) - (baseline.get('pr_auc', 0) or 0),\n",
    "            'delta_fpr': r.get('fpr', 0) - baseline.get('fpr', 0),\n",
    "            'delta_fnr': r.get('fnr', 0) - baseline.get('fnr', 0),\n",
    "        }\n",
    "        delta_rows.append(delta)\n",
    "    \n",
    "    df_delta = pd.DataFrame(delta_rows)\n",
    "    \n",
    "    # Save\n",
    "    delta_csv = TABLE_DIR / 'ablation_deltas.csv'\n",
    "    df_delta.to_csv(delta_csv, index=False)\n",
    "    atomic_save_json(delta_rows, TABLE_DIR / 'ablation_deltas.json')\n",
    "    \n",
    "    print(df_delta.to_string(index=False))\n",
    "    print(f'\\nSaved: {delta_csv}')\n",
    "    \n",
    "    # Key findings\n",
    "    print('\\n' + '=' * 80)\n",
    "    print('KEY FINDINGS')\n",
    "    print('=' * 80)\n",
    "    \n",
    "    # Largest F1 drop\n",
    "    worst = min(delta_rows, key=lambda x: x['delta_f1'])\n",
    "    print(f'  Largest F1 decrease: {worst[\"experiment\"]} (ΔF1 = {worst[\"delta_f1\"]:+.4f})')\n",
    "    \n",
    "    # Smallest F1 drop (most redundant)\n",
    "    best = max(delta_rows, key=lambda x: x['delta_f1'])\n",
    "    print(f'  Smallest F1 decrease: {best[\"experiment\"]} (ΔF1 = {best[\"delta_f1\"]:+.4f})')\n",
    "    \n",
    "    # TF-IDF vs Handcrafted\n",
    "    tfidf_only = next((r for r in all_results if r.get('name') == 'ablation_1_tfidf_only'), None)\n",
    "    hc_only = next((r for r in all_results if r.get('name') == 'ablation_2_handcrafted_only'), None)\n",
    "    if tfidf_only and hc_only:\n",
    "        print(f'  TF-IDF only F1: {tfidf_only.get(\"f1\", \"N/A\")}')\n",
    "        print(f'  Handcrafted only F1: {hc_only.get(\"f1\", \"N/A\")}')\n",
    "        if tfidf_only.get('f1', 0) > hc_only.get('f1', 0):\n",
    "            print(f'  -> TF-IDF alone performs better than handcrafted features alone')\n",
    "        else:\n",
    "            print(f'  -> Handcrafted features alone perform better than TF-IDF alone')"
]))

# =============================================================================
# CELL 14: Figures
# =============================================================================
cells.append(code([
    "print('Generating publication-quality figures...')\n",
    "\n",
    "# Filter completed results\n",
    "completed = [r for r in all_results if r.get('status') == 'completed']\n",
    "names = [r['name'].replace('ablation_', 'A').replace('_', ' ') for r in completed]\n",
    "accs = [r.get('accuracy', 0) for r in completed]\n",
    "f1s = [r.get('f1', 0) for r in completed]\n",
    "aucs = [r.get('roc_auc', 0) or 0 for r in completed]\n",
    "prs = [r.get('pr_auc', 0) or 0 for r in completed]\n",
    "fprs = [r.get('fpr', 0) for r in completed]\n",
    "fnrs = [r.get('fnr', 0) for r in completed]\n",
    "\n",
    "colors = ['#2196F3'] + ['#FF9800'] * (len(completed) - 1)\n",
    "\n",
    "# Figure 1: Performance comparison (grouped bar)\n",
    "fig, axes = plt.subplots(2, 2, figsize=(16, 12))\n",
    "fig.suptitle('Hybrid Guardrail V3 — Ablation Study Results', fontsize=18, fontweight='bold', y=1.02)\n",
    "\n",
    "# Accuracy\n",
    "ax = axes[0, 0]\n",
    "bars = ax.bar(range(len(names)), accs, color=colors, edgecolor='white', linewidth=0.5)\n",
    "ax.set_ylabel('Accuracy', fontsize=12)\n",
    "ax.set_title('Accuracy', fontsize=14, fontweight='bold')\n",
    "ax.set_xticks(range(len(names)))\n",
    "ax.set_xticklabels(names, rotation=45, ha='right', fontsize=8)\n",
    "ax.set_ylim(min(accs) - 0.05, max(accs) + 0.02)\n",
    "for bar, v in zip(bars, accs):\n",
    "    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.003,\n",
    "            f'{v:.3f}', ha='center', va='bottom', fontsize=7)\n",
    "ax.grid(axis='y', alpha=0.3)\n",
    "\n",
    "# F1\n",
    "ax = axes[0, 1]\n",
    "bars = ax.bar(range(len(names)), f1s, color=colors, edgecolor='white', linewidth=0.5)\n",
    "ax.set_ylabel('F1 Score', fontsize=12)\n",
    "ax.set_title('F1 Score', fontsize=14, fontweight='bold')\n",
    "ax.set_xticks(range(len(names)))\n",
    "ax.set_xticklabels(names, rotation=45, ha='right', fontsize=8)\n",
    "ax.set_ylim(min(f1s) - 0.05, max(f1s) + 0.02)\n",
    "for bar, v in zip(bars, f1s):\n",
    "    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.003,\n",
    "            f'{v:.3f}', ha='center', va='bottom', fontsize=7)\n",
    "ax.grid(axis='y', alpha=0.3)\n",
    "\n",
    "# ROC-AUC\n",
    "ax = axes[1, 0]\n",
    "bars = ax.bar(range(len(names)), aucs, color=colors, edgecolor='white', linewidth=0.5)\n",
    "ax.set_ylabel('ROC-AUC', fontsize=12)\n",
    "ax.set_title('ROC-AUC', fontsize=14, fontweight='bold')\n",
    "ax.set_xticks(range(len(names)))\n",
    "ax.set_xticklabels(names, rotation=45, ha='right', fontsize=8)\n",
    "ax.set_ylim(min(aucs) - 0.05, max(aucs) + 0.02)\n",
    "for bar, v in zip(bars, aucs):\n",
    "    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.003,\n",
    "            f'{v:.3f}', ha='center', va='bottom', fontsize=7)\n",
    "ax.grid(axis='y', alpha=0.3)\n",
    "\n",
    "# FPR\n",
    "ax = axes[1, 1]\n",
    "bars = ax.bar(range(len(names)), fprs, color=colors, edgecolor='white', linewidth=0.5)\n",
    "ax.set_ylabel('False Positive Rate', fontsize=12)\n",
    "ax.set_title('False Positive Rate (lower is better)', fontsize=14, fontweight='bold')\n",
    "ax.set_xticks(range(len(names)))\n",
    "ax.set_xticklabels(names, rotation=45, ha='right', fontsize=8)\n",
    "ax.set_ylim(0, max(fprs) + 0.02)\n",
    "for bar, v in zip(bars, fprs):\n",
    "    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.001,\n",
    "            f'{v:.3f}', ha='center', va='bottom', fontsize=7)\n",
    "ax.grid(axis='y', alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig(FIG_DIR / 'ablation_performance.png', dpi=300, bbox_inches='tight')\n",
    "plt.close()\n",
    "print('  Saved: ablation_performance.png')\n",
    "\n",
    "# Figure 2: AUC comparison\n",
    "fig, ax = plt.subplots(figsize=(14, 6))\n",
    "x = np.arange(len(names))\n",
    "w = 0.35\n",
    "ax.bar(x - w/2, aucs, w, label='ROC-AUC', color='#2196F3', edgecolor='white')\n",
    "ax.bar(x + w/2, prs, w, label='PR-AUC', color='#E91E63', edgecolor='white')\n",
    "ax.set_ylabel('AUC', fontsize=12)\n",
    "ax.set_title('ROC-AUC vs PR-AUC Across Ablations', fontsize=14, fontweight='bold')\n",
    "ax.set_xticks(x)\n",
    "ax.set_xticklabels(names, rotation=45, ha='right', fontsize=8)\n",
    "ax.legend(fontsize=10)\n",
    "ax.grid(axis='y', alpha=0.3)\n",
    "plt.tight_layout()\n",
    "plt.savefig(FIG_DIR / 'ablation_auc.png', dpi=300, bbox_inches='tight')\n",
    "plt.close()\n",
    "print('  Saved: ablation_auc.png')\n",
    "\n",
    "# Figure 3: F1 comparison\n",
    "fig, ax = plt.subplots(figsize=(14, 6))\n",
    "bars = ax.bar(range(len(names)), f1s, color=colors, edgecolor='white', linewidth=0.5)\n",
    "ax.set_ylabel('F1 Score', fontsize=12)\n",
    "ax.set_title('F1 Score Across Ablations', fontsize=14, fontweight='bold')\n",
    "ax.set_xticks(range(len(names)))\n",
    "ax.set_xticklabels(names, rotation=45, ha='right', fontsize=8)\n",
    "for bar, v in zip(bars, f1s):\n",
    "    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.002,\n",
    "            f'{v:.3f}', ha='center', va='bottom', fontsize=8)\n",
    "ax.grid(axis='y', alpha=0.3)\n",
    "plt.tight_layout()\n",
    "plt.savefig(FIG_DIR / 'ablation_f1.png', dpi=300, bbox_inches='tight')\n",
    "plt.close()\n",
    "print('  Saved: ablation_f1.png')\n",
    "\n",
    "# Figure 4: FPR comparison\n",
    "fig, ax = plt.subplots(figsize=(14, 6))\n",
    "bars = ax.bar(range(len(names)), fprs, color=colors, edgecolor='white', linewidth=0.5)\n",
    "ax.set_ylabel('False Positive Rate', fontsize=12)\n",
    "ax.set_title('False Positive Rate Across Ablations (lower is better)', fontsize=14, fontweight='bold')\n",
    "ax.set_xticks(range(len(names)))\n",
    "ax.set_xticklabels(names, rotation=45, ha='right', fontsize=8)\n",
    "for bar, v in zip(bars, fprs):\n",
    "    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.001,\n",
    "            f'{v:.3f}', ha='center', va='bottom', fontsize=8)\n",
    "ax.grid(axis='y', alpha=0.3)\n",
    "plt.tight_layout()\n",
    "plt.savefig(FIG_DIR / 'ablation_fpr.png', dpi=300, bbox_inches='tight')\n",
    "plt.close()\n",
    "print('  Saved: ablation_fpr.png')\n",
    "\n",
    "# Figure 5: Performance degradation from baseline\n",
    "if baseline:\n",
    "    fig, ax = plt.subplots(figsize=(14, 6))\n",
    "    delta_names = [r['name'].replace('ablation_', 'A').replace('_', ' ') for r in delta_rows]\n",
    "    delta_f1_vals = [d['delta_f1'] for d in delta_rows]\n",
    "    delta_colors = ['#4CAF50' if v >= 0 else '#F44336' for v in delta_f1_vals]\n",
    "    bars = ax.bar(range(len(delta_names)), delta_f1_vals, color=delta_colors, edgecolor='white')\n",
    "    ax.axhline(y=0, color='black', linewidth=0.5)\n",
    "    ax.set_ylabel('ΔF1 (relative to full baseline)', fontsize=12)\n",
    "    ax.set_title('Performance Degradation Relative to Full Baseline', fontsize=14, fontweight='bold')\n",
    "    ax.set_xticks(range(len(delta_names)))\n",
    "    ax.set_xticklabels(delta_names, rotation=45, ha='right', fontsize=8)\n",
    "    for bar, v in zip(bars, delta_f1_vals):\n",
    "        y_pos = bar.get_height() if v >= 0 else bar.get_height() - 0.003\n",
    "        ax.text(bar.get_x() + bar.get_width()/2, y_pos,\n",
    "                f'{v:+.3f}', ha='center', va='bottom' if v >= 0 else 'top', fontsize=8)\n",
    "    ax.grid(axis='y', alpha=0.3)\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(FIG_DIR / 'ablation_degradation.png', dpi=300, bbox_inches='tight')\n",
    "    plt.close()\n",
    "    print('  Saved: ablation_degradation.png')\n",
    "\n",
    "# Figure 6: Confusion matrices (grid)\n",
    "n_exp = len(completed)\n",
    "ncols = min(4, n_exp)\n",
    "nrows = (n_exp + ncols - 1) // ncols\n",
    "fig, axes = plt.subplots(nrows, ncols, figsize=(5 * ncols, 5 * nrows))\n",
    "if nrows == 1 and ncols == 1:\n",
    "    axes = np.array([[axes]])\n",
    "elif nrows == 1:\n",
    "    axes = axes.reshape(1, -1)\n",
    "elif ncols == 1:\n",
    "    axes = axes.reshape(-1, 1)\n",
    "\n",
    "for idx, r in enumerate(completed):\n",
    "    row, col = divmod(idx, ncols)\n",
    "    ax = axes[row, col]\n",
    "    cm_path = RESULTS_DIR / f'{r[\"name\"]}_confusion.json'\n",
    "    if cm_path.exists():\n",
    "        with open(cm_path) as f:\n",
    "            cm_data = json.load(f)\n",
    "        cm_ = np.array(cm_data['confusion_matrix'])\n",
    "        sns.heatmap(cm_, annot=True, fmt='d', cmap='Blues',\n",
    "                    xticklabels=['Safe', 'Malicious'], yticklabels=['Safe', 'Malicious'], ax=ax)\n",
    "    ax.set_title(r['name'].replace('ablation_', 'A').replace('_', ' '), fontsize=10)\n",
    "    ax.set_xlabel('Predicted'); ax.set_ylabel('True')\n",
    "\n",
    "# Hide unused subplots\n",
    "for idx in range(n_exp, nrows * ncols):\n",
    "    row, col = divmod(idx, ncols)\n",
    "    axes[row, col].set_visible(False)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig(FIG_DIR / 'ablation_confusion_matrices.png', dpi=300, bbox_inches='tight')\n",
    "plt.close()\n",
    "print('  Saved: ablation_confusion_matrices.png')\n",
    "\n",
    "# Figure 7: ROC curves overlay\n",
    "fig, ax = plt.subplots(figsize=(10, 8))\n",
    "for r in completed:\n",
    "    roc_path = RESULTS_DIR / f'{r[\"name\"]}_roc.json'\n",
    "    if roc_path.exists():\n",
    "        with open(roc_path) as f:\n",
    "            roc_data = json.load(f)\n",
    "        label = r['name'].replace('ablation_', 'A').replace('_', ' ')\n",
    "        ax.plot(roc_data['fpr'], roc_data['tpr'], linewidth=1.5,\n",
    "                label=f'{label} (AUC={roc_data[\"auc\"]:.4f})')\n",
    "ax.plot([0, 1], [0, 1], 'k--', linewidth=1, alpha=0.5, label='Random')\n",
    "ax.set_xlabel('False Positive Rate', fontsize=12)\n",
    "ax.set_ylabel('True Positive Rate', fontsize=12)\n",
    "ax.set_title('ROC Curves — All Ablations', fontsize=14, fontweight='bold')\n",
    "ax.legend(fontsize=7, loc='lower right')\n",
    "ax.grid(True, alpha=0.3)\n",
    "plt.tight_layout()\n",
    "plt.savefig(FIG_DIR / 'ablation_roc_curves.png', dpi=300, bbox_inches='tight')\n",
    "plt.close()\n",
    "print('  Saved: ablation_roc_curves.png')\n",
    "\n",
    "# Figure 8: PR curves overlay\n",
    "fig, ax = plt.subplots(figsize=(10, 8))\n",
    "for r in completed:\n",
    "    pr_path = RESULTS_DIR / f'{r[\"name\"]}_pr.json'\n",
    "    if pr_path.exists():\n",
    "        with open(pr_path) as f:\n",
    "            pr_data = json.load(f)\n",
    "        label = r['name'].replace('ablation_', 'A').replace('_', ' ')\n",
    "        ax.plot(pr_data['recall'], pr_data['precision'], linewidth=1.5,\n",
    "                label=f'{label} (AP={pr_data[\"ap\"]:.4f})')\n",
    "ax.set_xlabel('Recall', fontsize=12)\n",
    "ax.set_ylabel('Precision', fontsize=12)\n",
    "ax.set_title('Precision-Recall Curves — All Ablations', fontsize=14, fontweight='bold')\n",
    "ax.legend(fontsize=7, loc='lower left')\n",
    "ax.grid(True, alpha=0.3)\n",
    "plt.tight_layout()\n",
    "plt.savefig(FIG_DIR / 'ablation_pr_curves.png', dpi=300, bbox_inches='tight')\n",
    "plt.close()\n",
    "print('  Saved: ablation_pr_curves.png')\n",
    "\n",
    "print('All figures generated.')"
]))

# =============================================================================
# CELL 15: LaTeX Table
# =============================================================================
cells.append(code([
    "# Generate LaTeX table\n",
    "def generate_latex(results, baseline_r):\n",
    "    lines = []\n",
    "    lines.append(r'\\begin{table*}[t]')\n",
    "    lines.append(r'\\centering')\n",
    "    lines.append(r'\\caption{Ablation Study Results for Hybrid Guardrail V3. Bold values indicate the best performance in each column. $\\Delta$ values show the change relative to the full baseline (Ablation 0).}')\n",
    "    lines.append(r'\\label{tab:ablation}')\n",
    "    lines.append(r'\\small')\n",
    "    lines.append(r'\\begin{tabular}{l c c c c c c c c c}')\n",
    "    lines.append(r'\\toprule')\n",
    "    lines.append(r'\\textbf{Experiment} & \\textbf{Feat.} & \\textbf{Acc.} & \\textbf{Prec.} & \\textbf{Rec.} & \\textbf{F1} & \\textbf{ROC-AUC} & \\textbf{PR-AUC} & \\textbf{FPR} & \\textbf{FNR} \\\\')\n",
    "    lines.append(r'\\midrule')\n",
    "    \n",
    "    # Find best values\n",
    "    completed = [r for r in results if r.get('status') == 'completed']\n",
    "    best = {}\n",
    "    for metric in ['accuracy', 'precision', 'recall', 'f1', 'roc_auc', 'pr_auc']:\n",
    "        vals = [(r.get(metric, 0) or 0) for r in completed]\n",
    "        best[metric] = max(vals)\n",
    "    best['fpr'] = min((r.get('fpr', 1) or 1) for r in completed)\n",
    "    best['fnr'] = min((r.get('fnr', 1) or 1) for r in completed)\n",
    "    \n",
    "    def fmt(val, metric, bold=False):\n",
    "        if val is None:\n",
    "            return 'N/A'\n",
    "        s = f'{val:.4f}'\n",
    "        if bold and abs(val - best.get(metric, 0)) < 1e-6:\n",
    "            return f'\\\\textbf{{{s}}}'\n",
    "        return s\n",
    "    \n",
    "    for r in completed:\n",
    "        name = r['name'].replace('ablation_', '').replace('_', ' ')\n",
    "        nf = r.get('total_features', 0)\n",
    "        is_baseline = (r.get('name') == 'ablation_0_full')\n",
    "        \n",
    "        # Delta markers\n",
    "        delta_str = ''\n",
    "        if not is_baseline and baseline_r:\n",
    "            d_f1 = r.get('f1', 0) - baseline_r.get('f1', 0)\n",
    "            delta_str = f' ($\\Delta${d_f1:+.3f})' if abs(d_f1) > 1e-6 else ''\n",
    "        \n",
    "        row = (\n",
    "            f'{name}{delta_str} & {nf} '\n",
    "            f'& {fmt(r.get(\"accuracy\"), \"accuracy\", not is_baseline)} '\n",
    "            f'& {fmt(r.get(\"precision\"), \"precision\", not is_baseline)} '\n",
    "            f'& {fmt(r.get(\"recall\"), \"recall\", not is_baseline)} '\n",
    "            f'& {fmt(r.get(\"f1\"), \"f1\", not is_baseline)} '\n",
    "            f'& {fmt(r.get(\"roc_auc\"), \"roc_auc\", not is_baseline)} '\n",
    "            f'& {fmt(r.get(\"pr_auc\"), \"pr_auc\", not is_baseline)} '\n",
    "            f'& {fmt(r.get(\"fpr\"), \"fpr\", not is_baseline)} '\n",
    "            f'& {fmt(r.get(\"fnr\"), \"fnr\", not is_baseline)} '\n",
    "            f'\\\\\\\\'\n",
    "        )\n",
    "        lines.append(row)\n",
    "    \n",
    "    lines.append(r'\\bottomrule')\n",
    "    lines.append(r'\\end{tabular}')\n",
    "    lines.append(r'\\end{table*}')\n",
    "    return '\\n'.join(lines)\n",
    "\n",
    "latex = generate_latex(all_results, baseline)\n",
    "\n",
    "# Save\n",
    "tex_path = TABLE_DIR / 'ablation_results.tex'\n",
    "with open(tex_path, 'w') as f:\n",
    "    f.write(latex)\n",
    "print(f'Saved: {tex_path}')\n",
    "print('\\nLaTeX table:')\n",
    "print(latex)"
]))

# =============================================================================
# CELL 16: Research Interpretation
# =============================================================================
cells.append(md([
    "## Research Interpretation\n",
    "\n",
    "The following auto-generated summary interprets the ablation results under the evaluated setting."
]))

cells.append(code([
    "print('=' * 80)\n",
    "print('RESEARCH INTERPRETATION')\n",
    "print('=' * 80)\n",
    "\n",
    "if baseline is None:\n",
    "    print('WARNING: Baseline not available. Interpretation skipped.')\n",
    "else:\n",
    "    completed = [r for r in all_results if r.get('status') == 'completed']\n",
    "    \n",
    "    # 1. Which component removal caused the largest performance decrease?\n",
    "    if delta_rows:\n",
    "        worst = min(delta_rows, key=lambda x: x['delta_f1'])\n",
    "        print(f'\\n1. Largest F1 decrease from removing a component:')\n",
    "        print(f'   {worst[\"experiment\"]} produced a ΔF1 of {worst[\"delta_f1\"]:+.4f}.')\n",
    "        print(f'   This suggests that the removed component was associated with meaningful performance under the evaluated setting.')\n",
    "    \n",
    "    # 2. Which feature group appears most important?\n",
    "    if delta_rows:\n",
    "        worst = min(delta_rows, key=lambda x: x['delta_f1'])\n",
    "        print(f'\\n2. Most important feature group:')\n",
    "        print(f'   {worst[\"experiment\"]} (ΔF1 = {worst[\"delta_f1\"]:+.4f}) appears to be the most important feature group.')\n",
    "    \n",
    "    # 3. Which component contributes little?\n",
    "    if delta_rows:\n",
    "        best = max(delta_rows, key=lambda x: x['delta_f1'])\n",
    "        print(f'\\n3. Least important feature group:')\n",
    "        print(f'   {best[\"experiment\"]} (ΔF1 = {best[\"delta_f1\"]:+.4f}) appears to contribute little to overall performance.')\n",
    "    \n",
    "    # 4. How much does TF-IDF contribute?\n",
    "    tfidf_only = next((r for r in all_results if r.get('name') == 'ablation_1_tfidf_only'), None)\n",
    "    if tfidf_only and baseline:\n",
    "        d = tfidf_only.get('f1', 0) - baseline.get('f1', 0)\n",
    "        print(f'\\n4. TF-IDF contribution:')\n",
    "        print(f'   TF-IDF alone achieved F1={tfidf_only.get(\"f1\", 0):.4f} (ΔF1 = {d:+.4f} from full).')\n",
    "        if d > -0.05:\n",
    "            print(f'   Under the evaluated setting, TF-IDF appears to be the dominant signal.')\n",
    "        else:\n",
    "            print(f'   Under the evaluated setting, TF-IDF contributes meaningfully but not dominantly.')\n",
    "    \n",
    "    # 5. How much do handcrafted features contribute?\n",
    "    hc_only = next((r for r in all_results if r.get('name') == 'ablation_2_handcrafted_only'), None)\n",
    "    if hc_only and baseline:\n",
    "        d = hc_only.get('f1', 0) - baseline.get('f1', 0)\n",
    "        print(f'\\n5. Handcrafted features contribution:')\n",
    "        print(f'   Handcrafted features alone achieved F1={hc_only.get(\"f1\", 0):.4f} (ΔF1 = {d:+.4f} from full).')\n",
    "        if d > -0.05:\n",
    "            print(f'   Under the evaluated setting, handcrafted features appear to be a strong signal.')\n",
    "        else:\n",
    "            print(f'   Under the evaluated setting, handcrafted features contribute meaningfully.')\n",
    "    \n",
    "    # 6. Does the complete hybrid outperform simpler variants?\n",
    "    if tfidf_only and hc_only and baseline:\n",
    "        bf1 = baseline.get('f1', 0)\n",
    "        tf1 = tfidf_only.get('f1', 0)\n",
    "        hf1 = hc_only.get('f1', 0)\n",
    "        print(f'\\n6. Hybrid vs. simpler variants:')\n",
    "        print(f'   Full hybrid F1: {bf1:.4f}')\n",
    "        print(f'   TF-IDF only F1: {tf1:.4f}')\n",
    "        print(f'   Handcrafted only F1: {hf1:.4f}')\n",
    "        if bf1 > max(tf1, hf1):\n",
    "            print(f'   The full hybrid representation outperformed both simpler variants by {bf1 - max(tf1, hf1):.4f} F1 points.')\n",
    "        elif bf1 < max(tf1, hf1):\n",
    "            print(f'   Under the evaluated setting, the full hybrid did not outperform the best single-modality variant.')\n",
    "        else:\n",
    "            print(f'   The full hybrid performed comparably to the best single-modality variant.')\n",
    "    \n",
    "    # 7. Best complexity/performance tradeoff\n",
    "    if completed:\n",
    "        # Normalize: score = F1 - 0.001 * n_features (simple complexity penalty)\n",
    "        scored = [(r, r.get('f1', 0) - 0.0001 * r.get('total_features', 0)) for r in completed]\n",
    "        scored.sort(key=lambda x: x[1], reverse=True)\n",
    "        best_tradeoff = scored[0][0]\n",
    "        print(f'\\n7. Best performance/complexity tradeoff:')\n",
    "        print(f'   {best_tradeoff[\"name\"]} with {best_tradeoff.get(\"total_features\", 0)} features and F1={best_tradeoff.get(\"f1\", 0):.4f}')\n",
    "        print(f'   (under a simple linear complexity penalty of 0.0001 per feature)')\n",
    "\n",
    "print('\\n' + '=' * 80)\n",
    "print('NOTE: All interpretations are under the evaluated setting. Interaction')\n",
    "print('effects between feature groups may exist. A component that shows')\n",
    "print('little individual impact may still contribute through interactions.')\n",
    "print('=' * 80)"
]))

# =============================================================================
# CELL 17: Final Manifest Save
# =============================================================================
cells.append(code([
    "# Save final manifest with all results\n",
    "manifest = load_manifest()\n",
    "manifest['study_completed'] = True\n",
    "manifest['study_end_time'] = datetime.now().isoformat()\n",
    "manifest['total_experiments'] = len(EXPERIMENTS)\n",
    "manifest['completed_experiments'] = len([r for r in all_results if r.get('status') == 'completed'])\n",
    "manifest['failed_experiments'] = len([r for r in all_results if r.get('status') == 'failed'])\n",
    "manifest['dataset'] = DATASET_PATH\n",
    "manifest['seed'] = SEED\n",
    "manifest['split'] = '70/10/20 stratified'\n",
    "manifest['results_dir'] = str(RESULTS_DIR)\n",
    "manifest['figures_dir'] = str(FIG_DIR)\n",
    "manifest['tables_dir'] = str(TABLE_DIR)\n",
    "save_manifest(manifest)\n",
    "\n",
    "print('Final manifest saved.')\n",
    "print(f'\\nAll outputs in: {ABLATION_DIR}')\n",
    "print(f'  Results:   {RESULTS_DIR}')\n",
    "print(f'  Figures:   {FIG_DIR}')\n",
    "print(f'  Tables:    {TABLE_DIR}')\n",
    "print(f'  Manifests: {MANIFEST_DIR}')\n",
    "print('\\nABLATION STUDY COMPLETE.')"
]))

# =============================================================================
# Build notebook
# =============================================================================
notebook = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.10.0"
        }
    },
    "cells": cells
}

output_path = os.path.join(os.path.dirname(__file__), 'notebooks', 'hybrid_guardrail_v3_ablation.ipynb')
os.makedirs(os.path.dirname(output_path), exist_ok=True)
with open(output_path, 'w') as f:
    json.dump(notebook, f, indent=1)
print(f"Notebook written to: {output_path}")
print(f"Total cells: {len(cells)} ({sum(1 for c in cells if c['cell_type'] == 'code')} code, {sum(1 for c in cells if c['cell_type'] == 'markdown')} markdown)")
